### PR TITLE
fr-window: fix typo

### PR DESCRIPTION
**Pull request by raveit65**
Real fix for https://github.com/mate-desktop/engrampa/pull/216
Test with generating engrampa.pot in main dir.
`./autogen.sh && ./makepot`
After merging engrampa.pot can be updated and commited in github.
The resource file at transifex will be automatic updated from git.
And translators can update translations.

### CODE REVIEW

**Comment by houbaron** [comment]
LOL, I didn't find the real bug .

**Comment by houbaron** [comment]
So how to fix the Chinese [translation](https://github.com/mate-desktop/engrampa/blob/master/po/zh_CN.po?1536136505230#L1017)?

**Comment by raveit65** [comment]
This will be done at transifex server after we re-generate engrampa.pot, which is the base for the resource file for transifex.
https://www.transifex.com/mate/MATE/dashboard/
Create a account and become a member of the translation team of your language.
You will get an email notification if the resource file is update with fixed translation string and is waiting for translation.
That's it ;)

**Comment by sc0w** [comment]
`%'d` seems to work the same as `%d`

anyway, seems it is a typo

That code was added in the commit https://github.com/mate-desktop/engrampa/commit/37badab513ccac69db427207c1cd38ee57997449 based on file-roller commit https://gitlab.gnome.org/GNOME/file-roller/commit/bf2b5d2352cfcd9d4345dda7976208672838dce1

**Comment by raveit65** [comment]
engrampa.pot is updated https://github.com/mate-desktop/engrampa/commit/0c6a7a0f037c253a0fa88810bcab680e4a8c4f6e
I will cherry-pick https://github.com/mate-desktop/engrampa/commit/fc73b13df1e78117e2f035e3fd7e49d1cd1fb62b to 1.20 as it is a bugfix.
When we pull fixed translations back from transifex we need to test this issue again with the new translation, before we make a new release.
I hope i don't forget this :)

**Comment by jtojnar** [comment]
The apostrophe was likely intentional, see https://en.wikipedia.org/wiki/Printf_format_string#Flags_field:

> <table><tr><td>'(apostrophe)</td> <td>The integer or exponent of a decimal has the thousands grouping separator applied.</td></tr></table>

**Pull request merged**
