### PR TITLE
Add ARC archive support

### PR DESCRIPTION
**Pull request by rbuj**
You can use EGACHESS.ARC file for testing from #347

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
Can you please update PR to fix merge conflict?

**Comment by rbuj** [comment]
@raveit65 done

**Comment by rbuj** [comment]
@lukefromdc install `nomarch` package and run the commands below:
```shell
$ sudo dnf install -y nomarch
$ sudo update-mime-database /usr/share/mime
$ sudo update-desktop-database /usr/share/applications
```

**Comment by lukefromdc** [comment]
Can't use the first of those exact commands: we don't have DNF in Debian. I will have to look for nomarch in Synaptic and see if we have it or a similar package.

**Comment by raveit65** [comment]
> Can't use the first of those exact commands: we don't have DNF in Debian. I will have to look for nomarch in Synaptic and see if we have it or a similar package.

Dnf is a command line tool in fedora, similar to apt or aptitude in debian.
A lot of options are the same, eg.
dnf search ...... = aptitude search ......
If you know to use apt or aptitude , you should able to use dnf, or the other way around.

**Pull request merged**
