### PR TITLE
file-utils: drop uricmp

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by zhuyaliang — APPROVED** [review]

**Review by zhuyaliang — APPROVED** [review]

**Comment by zhuyaliang** [comment]
Use the existing function ```g_strcmp0``` will be better

**Review by zhuyaliang — APPROVED** [review]
Agree to this change

**Comment by zhuyaliang** [comment]
@rbuj Can you fix the conflict? I plan to merge this PR

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine

**Comment by lukefromdc** [comment]
This needs a conflict resolution

**Pull request closed without merging**
