### PR TITLE
Update authors

### PR DESCRIPTION
**Pull request by rbuj**
```
$ git diff --word-diff=color --word-diff-regex=. master
```

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
I agree with @vkareh to remove the noreply.github.com adresses.
In general all addresses should be valid, IHMO.

**Comment by rbuj** [comment]
The `noreply.github.com` contains the github username as noted in
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address.

In case the user decides to keep private the actual email address, the username on github helps to identity the user on github preventing identity theft.

**Comment by raveit65** [comment]
But we can identify this user as author.
You can also write XXX or xyz as author name, it's just the same as noreply.github.com

**Comment by vkareh** [comment]
> In case the user decides to keep private the actual email address, the username on github helps to identity the user on github preventing identity theft.

Then can you regexp replace the noreply email to their github page? Otherwise users will see a mailto link that points to a noreply address

**Comment by rbuj** [comment]
@vkareh done

**Pull request merged**
