### PR TITLE
Add the ability to support 'unar' over .zip archives

### PR DESCRIPTION
**Pull request by sc0w**
Closes https://github.com/mate-desktop/engrampa/issues/210

### CODE REVIEW

**Comment by sc0w** [comment]
It works here:

screenshot at 2018-08-03 11-41-59

screenshot at 2018-08-03 11-42-13

**Comment by sc0w** [comment]
Little more changes: if the key is TRUE, and 'unar' isn't installed, engrampa ignore it and sets the key to FALSE:

```patch
diff --git a/src/fr-command-7z.c b/src/fr-command-7z.c
index b018d39..33e3b3b 100644
--- a/src/fr-command-7z.c
+++ b/src/fr-command-7z.c
@@ -598,8 +598,11 @@ fr_command_7z_get_mime_types (FrCommand *comm)
 	GSettings *settings;
 	settings = g_settings_new ("org.mate.engrampa.general");
 
-	if (g_settings_get_boolean (settings, "unar-open-zip"))
+	if (g_settings_get_boolean (settings, "unar-open-zip") &&
+	    is_program_in_path ("unar") && is_program_in_path ("lsar"))
 		sevenz_mime_types [8] = NULL;
+	else
+		g_settings_set_boolean (settings, "unar-open-zip", FALSE);
 
 	g_object_unref (settings);
 
diff --git a/src/fr-command-zip.c b/src/fr-command-zip.c
index 0b46150..387f27c 100644
--- a/src/fr-command-zip.c
+++ b/src/fr-command-zip.c
@@ -402,8 +402,11 @@ fr_command_zip_get_mime_types (FrCommand *comm)
 	GSettings *settings;
 	settings = g_settings_new ("org.mate.engrampa.general");
 
-	if (g_settings_get_boolean (settings, "unar-open-zip"))
+	if (g_settings_get_boolean (settings, "unar-open-zip") &&
+	    is_program_in_path ("unar") && is_program_in_path ("lsar"))
 		zip_mime_type [10] = NULL;
+	else
+		g_settings_set_boolean (settings, "unar-open-zip", FALSE);
 
 	g_object_unref (settings);
```

**Comment by raveit65** [comment]
Test instruction please?

**Comment by sc0w** [comment]
@jackssirs 1.16? this PR is only for master branch, did you build the packages?

@raveit65 

> Test instruction please?

1. install `unar`
2. make sure the commands `unar` and `lsar` work in terminal
3. install this PR, goes to / org / mate / engrampa /general
4. set `unar-open-zip` to ON
5. try to open the file [CyrilicArch.zip](https://github.com/mate-desktop/engrampa/files/2293426/CyrilicArch.zip) and see if the fonts are displayed like the screenshots in my previous comments

@vkareh 

> Is there any build flag that I need to pass to ./configure to get proper unar support?

I just build the debian packages and it works here: [packages_pr.zip](https://github.com/mate-desktop/engrampa/files/2293443/packages_pr.zip)

**Comment by vkareh** [comment]
@sc0w - even installing your debs I get the same issue as on my screenshot. I wonder if this is a locale or encoding issue? I only have en_US and es_PR installed... I also tried changing the system font and no luck

**Comment by vkareh** [comment]
@sc0w - wait, disregard my previous message. I had forgotten to enable the unrar gsettings with your debs and now it works (still doesn't work when I build it locally though...)

**Comment by lukefromdc** [comment]
Local build also worked

**Pull request merged**
