### PR TITLE
deprecations

### PR DESCRIPTION
**Pull request by raveit65**
Please test and review.

### CODE REVIEW

**Comment by sc0w** [comment]
With this branch, on a terminal, with: **engrampa filecompressed** I see this:

`(engrampa:4088): Gtk-WARNING **: Allocating size to FrWindow 0x556e4713c2a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?`

This is normal?

With the branch master I dont see this

**Comment by raveit65** [comment]
This is a very stupid warning introduced with gtk+-3.20 which warns in all applications .
How does it work before?
What did you do exactly to trigger this?.
I get some similar one about the Scrolledwindow if i create a new achieve or open an existing one,  but i don't know to see this warning.
And can you please test the first and the last commit as single patch, to see at which place the warning is caused.

**Comment by sc0w** [comment]
https://github.com/mate-desktop/engrampa/pull/152/commits/ac3ce63f022bcc573c875a2e4f91f46cc77cb7ac causes warning

> I get some similar one about the Scrolledwindow if i create a new achieve or open an existing one, but i don't know to see this warning.

me too

> What did you do exactly to trigger this?

Opening an existing file compressed, I see the warning about `FrWindow` and `GtkScrolledWindow`

> How does it work before?

Like you, only the warning about `GtkScrolledWindow`

**Comment by raveit65** [comment]
Hmm, opening an existing compressed file doesn't give me the warning wit fr-window.
 ```
[rave@mother test]$ engrampa test-1.tar.gz 

(engrampa:3179): Gtk-WARNING **: Allocating size to GtkScrolledWindow 0x558a35a302b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

**Comment by raveit65** [comment]
@monsta @flexiondotorg 
Can you please test too?
I do not understand which command or situation should trigger the in comment 2 mentioned warning.
'engrampa test-1.tar.gz' do not trigger this warning here.

**Comment by sc0w** [comment]
gtk 3.21.5

```
$ engrampa test.tar.gz 

(engrampa:18361): Gtk-WARNING **: Allocating size to FrWindow 0x564cde15e2a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(engrampa:18361): Gtk-WARNING **: Allocating size to GtkScrolledWindow 0x564cde3462c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

**Comment by raveit65** [comment]
Ok, i'm using stable 3.20.x, maybe that does make the different.

**Comment by raveit65** [comment]
Wtf, with 3.21.x i get this warning too. Let see what i can do.

**Comment by lukefromdc** [comment]
Just tested with GTK 3.21, got only these warnings and good general behavior:
```

(engrampa:1940): Gtk-WARNING **: Allocating size to FrWindow 0x1cf0340 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(engrampa:1940): Gtk-WARNING **: Allocating size to GtkScrolledWindow 0x1d403f0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

```

**Comment by raveit65** [comment]
The warning about FrWindow i caused by changes in this file.
https://github.com/mate-desktop/engrampa/pull/152/commits/ac3ce63f022bcc573c875a2e4f91f46cc77cb7ac#diff-323a9cb3946850419e43e05b60100e9dR5376
But i don't know at which place i should add 'gtk_widget_get_preferred_width'.
In general those are only warnings which don't break the functionality, because in older gtk+versions they are not there.
Also, this change is from 2012 https://git.gnome.org/browse/file-roller/commit/?id=2434158834117f4b3bbbf894ed2706561b7a61b1 and did work for 4 years.
It's only an idea from gtk+ devs to warn at those places all over gtk+ applications.

**Comment by raveit65** [comment]
So adding gtk_widget_get_preferred_width and gtk_widget_get_preferred_height in fr_window_attach () function doesn't make any different.
I'm a bit clueless where and how to add this.

**Comment by lukefromdc** [comment]
That "warningg" seems to be borderline spam from GTK devs who don't
like any  other way of setting these dimensions.

**Comment by sc0w** [comment]
file-roller uses gtk_widget_get_preferred_size:

https://github.com/GNOME/file-roller/commit/f6b6f4f7022a41c59ab302a1ab2878184b834396#diff-84e3cb58cd733dc91dd33ae3581a6148R190

anyway, engrampa works fine with the two warnings

**Comment by raveit65** [comment]
This is not fr-windows.c and gtk_widget_get_preferred_width and gtk_widget_get_preferred_height !

**Comment by sc0w** [comment]
`file-roller` have no warnings, and I can't see `gtk_widget_get_preferred_width` or `gtk_widget_get_preferred_height` on the code

**Comment by monsta** [comment]
Seems to work fine. I get the same warning about ```FrWindow``` with 3.21, so nothing new to add here. I think it can be merged.

**Comment by raveit65** [comment]
i tried https://git.gnome.org/browse/file-roller/commit/?id=cfdfeb566244d5b08a13b8c7e3033a020cd91237 without luck.
@sc0w 
do you agree with merging it with that warning?

**Comment by lukefromdc** [comment]
There are two of those warnings with the PR-but one of them without this
PR anyway. Also and more importantly, for me this stops a segfault on
closing engrampa. I'm using it here locally,

**Comment by sc0w** [comment]
@raveit65 yes, I have no problem :)

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/engrampa/commit/0ac35b0a6a21f62d8fbdfdcb7358a8d088b3c92b
https://github.com/mate-desktop/engrampa/commit/43ff5a233282bcd00ed36088c16cabe5255d10db
https://github.com/mate-desktop/engrampa/commit/701085ca2e9ffea9a9042e174f76c70038a85b33

**Pull request closed without merging**
