### PR TITLE
Update FSF address

### PR DESCRIPTION
**Pull request by tamplan**
Update [FSF address](https://www.fsf.org/about/contact/)

### CODE REVIEW

**Comment by rbuj** [comment]
This line should be ` * write to the Free Software Foundation, Inc., 51 Franklin Street,`
https://github.com/mate-desktop/engrampa/blob/1539e39e8e311f7b262bf25eb222f1e1eaac1858/copy-n-paste/eggdesktopfile.c#L20

Modify the file using your preferred editor (i.e. nano), next add the changes, amend the commit and finally force the update of the PR:
```
nano copy-n-paste/eggdesktopfile.c
git add copy-n-paste/eggdesktopfile.c
git commit --amend
git push -f

**Comment by tamplan** [comment]
Done :-)

Thanks for help!

**Comment by rbuj** [comment]
@tamplan I recommend you to use branches on your local working copy:

1. clone your repo `git clone git@github.com:tamplan/engrampa.git`
2. set up upstream, if you didn't do it before `git remote add upstream https://github.com/mate-desktop/engrampa.git`
3. fetch changes from upstream `git fetch upstream`
4. checkout the development branch `git checkout master`
5. merge working copy with upstream `git merge upstream/master`
6. update your remote repo `git push`
7. create a new branch `git checkout -b new-branch` (new-branch is the name of your new branch)
8. edit/modify file(s) on your working dir
9. add changes `git add file(s)`
10. set commit message `git commit -m "This is the title of the commit"`
11. add a commit description `git commit --amend` (1st line is the title)
12. send changes to your remote `git push origin new-branch` (new-branch: step 7)
13. go to https://github.com/mate-desktop/engrampa.git and create a pull request

Note: you can create a separate PR, to do it, first `git checkout master` next continue on step 7.

**Comment by tamplan** [comment]
I have done test with branch to develop but merge the branch to master by error.
Any way, thanks for help.

**Comment by raveit65** [comment]
I have a deja vu :)
```
- *  Foundation, Inc., 59 Temple Street #330, Boston, MA 02110-1301, USA.
+ *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
```
...missing comma after  `MA 02110-1301`

Any way, i don`t care about address in the states since their fascist president Trump don`t care about europe, china, mexico and the rest of the world :P

**Comment by tamplan** [comment]
Right for the missing comma and the rest too...

Thanks!

**Pull request merged**
