### PR TITLE
Use mate-compiler-flags.m4 provided by mate-common

### PR DESCRIPTION
**Pull request by rbuj**
USAGE: ./autogen.sh --enable-compile-warnings=no/minimum/yes/maximum/error@

If --enable-compile-warnings is not provided, the default is --enable-compile-warnings=yes

It requires https://github.com/mate-desktop/mate-common/pull/27, plus autoconf-archive package on build.

### CODE REVIEW

**Comment by raveit65** [comment]
I think i will make a mate-common-1.23.1 release. Than we can build from new tarball in travis for all distros. Example travis config (before_scripts)
see https://github.com/mate-desktop/mate-settings-daemon/blob/master/.travis.yml#L202
```
 - cd ${START_DIR}
  - '[ -f mate-common-1.23.1.tar.xz ] || curl -Ls -o mate-common-1.23.1.tar.xz http://pub.mate-desktop.org/releases/1.23/mate-common-1.23.1.tar.xz'
  - tar xf mate-common-1.23.1.tar.xz
  - cd mate-common-1.23.1
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu --enable-compile-warnings=maximum
  - else
  -     ./configure --prefix=/usr --enable-compile-warnings=maximum
  - fi
  - make
  - make install
```
@rbuj @mate-desktop/core-team 
What do you think?

**Comment by raveit65** [comment]
mate-common-1.23.0 is released we can use it now for travis (ci).

**Comment by rbuj** [comment]
I agree and I think it's a great idea, mate-common should be installed from source on travis machines before running mate-autogen from autogen.sh

**Comment by rbuj** [comment]
It does not make sense to use `--enable-compile-warnings=maximum` for installing mate-common from tarball:
```shell
$ ./configure --prefix=/usr --enable-compile-warnings=maximum
...
configure: WARNING: unrecognized options: --enable-compile-warnings
```

**Comment by raveit65** [comment]
weird, this works for me with `warnings` branch.
```
[rave@mother engrampa-dist]$ rpm -qa mate-common
mate-common-1.23.0-1.fc30.noarch
[rave@mother engrampa-dist]$ rpm -qa autoconf*
autoconf-archive-2019.01.06-2.fc30.noarch
autoconf-2.69-31.fc30.noarch
[rave@mother engrampa-dist]$ ./autogen.sh

<cut>

[rave@mother engrampa-dist]$ ./configure --enable-compile-warnings=maximum
checking for a BSD-compatible install... /usr/bin/install -c
<cut>
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking whether C compiler accepts -Werror=unknown-warning-option... no
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wbad-function-cast... yes
checking whether C compiler accepts -Wcast-align... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wformat-nonliteral... yes
checking whether C compiler accepts -Wmissing-declarations... yes
checking whether C compiler accepts -Wmissing-field-initializers... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wredundant-decls... yes
checking whether C compiler accepts -Wshadow... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Werror=format-security... no
checking whether C compiler accepts -Wno-sign-compare... yes
checking flags to pass to the C compiler gcc... -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wno-sign-compare
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
```
I see all compiler options from new mate-common.

**Comment by raveit65** [comment]
You're right, misunderstanding.....
Running `--enable-compile-warnings=maximum` for mate-common is useless, wrong posting by me.

I meant to use `--enable-compile-warnings=maximum` for compiling engrampa.

**Comment by raveit65** [comment]
(before_scripts)
```
 - cd ${START_DIR}
  - '[ -f mate-common-1.23.0.tar.xz ] || curl -Ls -o mate-common-1.23.0.tar.xz http://pub.mate-desktop.org/releases/1.23/mate-common-1.23.0.tar.xz'
  - tar xf mate-common-1.23.0.tar.xz
  - cd mate-common-1.23.0
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install
```

**Comment by raveit65** [comment]
I think i t needs to add to (build_scripts:) in travis.yml
https://github.com/mate-desktop/engrampa/blob/master/.travis.yml#L155
```
./autogen.sh --enable-compile-warnings=maximum
```
not sure, it needs to be tested.
Should i made a commit for this here in PR?

**Comment by raveit65** [comment]
I added new mate-common to travis builds.

**Comment by raveit65** [comment]
@rbuj 
I think we need to add autoconf-archive as require to configure.ac, otherwise a local build will fail.

**Comment by rbuj** [comment]
@raveit65 I think that we can check if the AX_CHECK_COMPILE_FLAG, AX_APPEND_FLAG macros are available on the system modifying mate-common:
```patch
diff --git a/macros/mate-compiler-flags.m4 b/macros/mate-compiler-flags.m4
index 6ba33be..fefe474 100644
--- a/macros/mate-compiler-flags.m4
+++ b/macros/mate-compiler-flags.m4
@@ -23,6 +23,14 @@ AC_DEFUN([MATE_COMPILE_WARNINGS],[
     dnl More compiler warnings
     dnl ******************************
 
+    m4_ifndef([AX_CHECK_COMPILE_FLAG],[
+        AC_MSG_ERROR([You need to install the autoconf-archive package.])
+    ])
+
+    m4_ifndef([AX_APPEND_FLAG],[
+        AC_MSG_ERROR([You need to install the autoconf-archive package.])
+    ])
+
     AC_ARG_ENABLE(compile-warnings,
                   AS_HELP_STRING([--enable-compile-warnings=@<:@no/minimum/yes/maximum/error@:>@],
                                  [Turn on compiler warnings]),,
```
Test:
```shell
$ ./autogen.sh --prefix=/usr
...
configure: error: You need to install the autoconf-archive package.
```

**Comment by raveit65** [comment]
@rbuj 
I think this is Ok, than it is ready to go.

**Comment by rbuj** [comment]
PR https://github.com/mate-desktop/mate-common/pull/28

**Comment by raveit65** [comment]
travis.yml update for mate-common-1.23.1

**Comment by raveit65** [comment]
Travis is updated to use latest mate-common release.

**Pull request merged**
