### PR TITLE
Add MIME aliases for gzip and bzip2

### PR DESCRIPTION
**Pull request by gber**
The application/gzip alias is e.g. specified by FileRoller and Ark, application/bzip2 is specified by FileRoller.

If another archiver is installed these aliases seem to be preferred and it is not possible to override the association in a `mimeapps.list` file if engrapa's desktop file doesn't provide them.

### CODE REVIEW

**Review by zhuyaliang — APPROVED** [review]
Agree to add a new mimetype

**Review by lukefromdc — APPROVED** [review]
On my long-established system (nothing like a new empty user of course) on Debian Unstable I didn't notice any behavioral change from this: I have file-roller installed and never had a problem with engrampa not being selectable for the application to open .gz files with. No idea what the default was after so many years though.

**Comment by lukefromdc** [comment]
Called for another review if possible as I simply don't know much about this

**Review by cwendling — APPROVED** [review]
You could add [`application/x-bzip2`](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/master/data/freedesktop.org.xml.in#L1605) that is missing as well, but otherwise looks good.

**Comment by gber** [comment]
> You could add [`application/x-bzip2`](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/master/data/freedesktop.org.xml.in#L1605) that is missing as well, but otherwise looks good.

Added.

**Pull request merged**
