### PR TITLE
Support .udeb package format

### LINKED ISSUE #246: Support Debian udeb packages
#### Expected behaviour
Using engrampa to open file with ending .udeb should display contents, as with .deb file.

#### Actual behaviour
Fails to open archive, with message: "Archive type not supported".
If archive is renamed with .deb ending, then contents are displayed normally. (udeb and deb are essentially the same file type.)

#### Steps to reproduce the behaviour
As above.

#### MATE general version
N/A 

#### Package version
1.20.2

#### Linux Distribution
Debian Stretch 9.7

#### Link to downstream report of your Distribution
(none)

Since the two file types (.deb and .udeb) are essentially the same, maybe something similar to the recent fix for handling .a files as .ar would be sufficient for this? https://github.com/mate-desktop/engrampa/commit/499e600d758578eeb8187f92d0c12b36e50f7595

### PR DESCRIPTION
**Pull request by vkareh**
This enables support for udeb (micro-deb) files, which are a package format used during bootstrapping a Debian installation. They have the same mimetype as regular deb files.

Fixes #246

### CODE REVIEW

**Comment by rbuj** [comment]
@vkareh 
I suggest you to use "application/vnd.debian.binary-package" instead of "application/x-deb", it is also applicable to .deb file extension.
https://www.iana.org/assignments/media-types/application/vnd.debian.binary-package

**Comment by vkareh** [comment]
@rbuj - good point. I've changed it and it works well, thanks!

I also added another commit that cleans up the list of mime-types and their descriptions

**Comment by lukefromdc** [comment]
I have no idea at all how to test this, as I normally build debs either with Checkinstall or with Debian's files (for their unmodified packages) and dpkg-buildpackage.

**Comment by vkareh** [comment]
@lukefromdc - here's what I used: https://packages.debian.org/stretch/amd64/alsa-utils-udeb/download
 download a random .udeb file from the debian website and use that.

**Pull request merged**
