### PR TITLE
dlg-package-installer: Don't build the path to packages.match

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Ok, all three PRs are building fine with --enable-PackageKit, but can you please explain how to use `packages.match` with Packagekit?

**Comment by rbuj** [comment]
The system prompts the user to install the required packages when the binary file isn't found on the system, and distributions may change the package name.

Test:

- Remove p7zip p7zip-plugins packages:
```
$ sudo dnf remove -y p7zip p7zip-plugins
```
- Override the package name that provides 7za command:
```
$ grep p7zip data/packages.match
p7zip=test-package
p7zip-full=
p7zip-rar=
```
- Try to open a 7z file.

- Click on Search Command button, next click on Find in Software button:

Screenshot at 2021-02-27 12-26-56

Software will try to install `test-package`:

Screenshot at 2021-02-27 12-21-47

**Comment by raveit65** [comment]
Hmm,
after clicking on `search command" i get this error.
Bildschirmfoto zu 2021-02-27 15-54-32

**Comment by rbuj** [comment]
@raveit65 you need to install `gnome-software`

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
