### PR TITLE
fr-archive: fix mime-type for 'tar.Z' files in local magic

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by rbuj** [comment]
A single file compressed using compress is **NOT** a tar archive compressed with compress:
````
$  compress -f text.txt
$  hexdump -C -n 2 text.txt.Z
00000000  1f 9d                                             |..|
00000002
```

**Comment by sc0w** [comment]
the tests:

rename the file `README.tar.Z` inside the file [test.zip](https://github.com/mate-desktop/engrampa/files/3685202/test.zip) to `tarztest`

build without `--enable-magic` with this additional change (because the two lines are never read) and open `tarztest` , the file opens fine:

```patch
diff --git a/src/fr-archive.c b/src/fr-archive.c
index bef5cad..2b1f530 100644
--- a/src/fr-archive.c
+++ b/src/fr-archive.c
@@ -1154,7 +1154,7 @@ load_local_archive (FrArchive  *archive,
 
 	old_command = archive->command;
 
-	mime_type = get_mime_type_from_filename (archive->local_copy);
+	mime_type = get_mime_type_from_magic_numbers (archive->local_copy);
 	if (! create_command_to_load_archive (archive, mime_type)) {
 		mime_type = get_mime_type_from_content (archive->local_copy);
 		if (! create_command_to_load_archive (archive, mime_type)) {

**Comment by sc0w** [comment]
what is compress? what is the name of package in your system?

**Comment by rbuj** [comment]
> what is compress? what is the name of package in your system?

https://packages.debian.org/sid/amd64/ncompress/filelist

**Pull request closed without merging**
