### PR TITLE
actions: expand the comment on about dialog

### PR DESCRIPTION
**Pull request by rbuj**
### Before

Screenshot at 2020-03-31 17-29-13

### After

Screenshot at 2020-03-31 17-40-22

### CODE REVIEW

**Comment by rbuj** [comment]
The comment is pulled from https://mate-desktop.org/

**Comment by sc0w** [comment]
again, I don't like this change, the about dialogs must to be little, we have more info in the help

**Comment by rbuj** [comment]
@sc0w following the general directions of gtk https://developer.gnome.org/gtk3/stable/GtkAboutDialog.html#GtkAboutDialog--comments

Screenshot at 2020-03-31 20-18-50

**Comment by sc0w** [comment]
Thanks to make it simpler.

I think it isn't needed to mention it twice in the dialog:

```
Engrampa

1.24.0

Engrampa is ... .. ..
```

I think is better with just:

`An archive manager for the MATE Desktop Environment.`

instead

`Engrampa is an archive manager for the MATE Desktop Environment.`

or just: `'An archive manager'` because it works in more desktop environments

**Comment by rbuj** [comment]
@sc0w where is the verb in `An archive manager for the MATE Desktop Environment`?

**Comment by raveit65** [comment]
I think it is a good idea to use the name engrampa, a user could be confused and think it is file-roller without that marketing, or not?
I don't really understand what is bad to use the name........

**Comment by sc0w** [comment]
@rbuj why you need a verb? The description doesn't need a verb

In the about dialog the name of program only needs to mention one time, in my opinion. The next sentence is a description, it is redundant to mentioned engrampa again.

But I have no problem if others like to merge it :)

[offtopic] the engrampa icon is a reference to file-roller, I think it is good to change it in the future [/offtopic]

**Pull request merged**
