### PR TITLE
deprecation fixes

### PR DESCRIPTION
**Pull request by raveit65**
Note, i am not really sure if all that ui files are used.....

### CODE REVIEW

**Comment by sc0w** [comment]
@raveit65 

`fr-window.c` Did you forget to delete the commented lines after your tests?

`password.ui` (edit->password) seems to be better with this PR

without the PR

passwordbefore

with the PR

passwordlater

`delete.ui` (pressing key DEL in a folder/file) I see the same than @lukefromdc 

without the PR

deletebefore

with the PR

deleteafter

**Comment by raveit65** [comment]
> fr-window.c Did you forget to delete the commented lines after your tests?

Opps, the commented lines are deleted now.

> password.ui (edit->password) seems to be better with this PR

Yes, i added "max_width_chars">70 for the "Note......." label.
I think 70 chars is a good value, i will use that for other applications too.

**Comment by raveit65** [comment]
delete.ui;
For some reasons the GtkEntry doesn't expand over the column width here after porting GtkTable to GtkGrid. The result looks like that. (proposal 1)
engrampa-delete-ui-after-grid
In previous comment i packed the GtkLabel Files and the GtkEntry in a horizontal GtkBox. which breaks the Checkboxes.
It's possible to set a width request for the GtkEntry (proposal 2)
engrampa_delete-ui-entry-large
I can also revert the whole commit and we use deprecated Gtkable here (proposal 3), sorry i've no idea to do that better.
Thoughts?

**Comment by raveit65** [comment]
I found a fix for delete.ui, now it looks like this.
engrampa-delete-ui-fixed
PR is rebased, please test again,

**Comment by lukefromdc** [comment]
This now works, the radion button problem in the delete dialog is fixed

**Pull request merged**
