### PR TITLE
dlg-prop: show the exact number of bytes as part of the size

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@sc0w 
You like that?

**Comment by sc0w** [comment]
It makes sense, because caja shows too the value in bytes into the properties dialog.

btw, I don't understand why I can't see the "**,**" separator like the @lukefromdc screenshot

**Comment by raveit65** [comment]
@sc0w 
Did you test it with another theme?
With Menta:
Bildschirmfoto zu 2019-09-17 08-40-23

**Comment by sc0w** [comment]
no, it doesn't work with menta (the thousands separator)

**Comment by raveit65** [comment]
@sc0w 
Do you think it is a issue with PR or can we merge it?

**Comment by sc0w** [comment]
not related, merging...

**Pull request merged**
