### PR TITLE
Replace special "#" and "?" characters in uri

### LINKED ISSUE #501: engrampa hangs when using --extract-here with certain archives
#### Expected behaviour
engrampa successfully extracts files from the archive and exits

#### Actual behaviour
engrampa hangs when using `--extract-here` with certain archives.

The hang does not occur when using `--extract` or `--extract-to`.

#### Steps to reproduce the behaviour
1 - Create a new empty folder named `testcase`
2 - Save [engrampa-hang.tar](https://github.com/correctmost/issue-attachments/blob/main/engrampa/engrampa-hang.tar) in the `testcase` directory
3 - Run `engrampa --extract-here engrampa-hang.tar` from `testcase/` to trigger a hang

##### Backtrace of the hanging thread

```
Thread 1 "engrampa" received signal SIGINT, Interrupt.
statx (fd=fd@entry=-100, path=path@entry=0x555555a23a80 "/home/s/Downloads/testcase", flags=flags@entry=2304, mask=mask@entry=4095, buf=buf@entry=0x7fffffffc6d0) at ../sysdeps/unix/sysv/linux/statx.c:28
28        int ret = INLINE_SYSCALL_CALL (statx, fd, path, flags, mask, buf);                                                                                                                                                                  
(gdb) bt
#0  statx (fd=fd@entry=-100, path=path@entry=0x555555a23a80 "/home/s/Downloads/testcase", flags=flags@entry=2304, mask=mask@entry=4095, buf=buf@entry=0x7fffffffc6d0) at ../sysdeps/unix/sysv/linux/statx.c:28
#1  0x00007ffff73f9f64 in g_local_file_statx
    (stat_buf=0x7fffffffc6d0, mask_required=(G_LOCAL_FILE_STAT_FIELD_TYPE | G_LOCAL_FILE_STAT_FIELD_MODE | G_LOCAL_FILE_STAT_FIELD_NLINK | G_LOCAL_FILE_STAT_FIELD_UID | G_LOCAL_FILE_STAT_FIELD_GID | G_LOCAL_FILE_STAT_FIELD_MTIME | G_LOCAL_FILE_STAT_FIELD_CTIME | G_LOCAL_FILE_STAT_FIELD_INO | G_LOCAL_FILE_STAT_FIELD_SIZE | G_LOCAL_FILE_STAT_FIELD_BLOCKS), mask=(G_LOCAL_FILE_STAT_FIELD_TYPE | G_LOCAL_FILE_STAT_FIELD_MODE | G_LOCAL_FILE_STAT_FIELD_NLINK | G_LOCAL_FILE_STAT_FIELD_UID | G_LOCAL_FILE_STAT_FIELD_GID | G_LOCAL_FILE_STAT_FIELD_ATIME | G_LOCAL_FILE_STAT_FIELD_MTIME | G_LOCAL_FILE_STAT_FIELD_CTIME | G_LOCAL_FILE_STAT_FIELD_INO | G_LOCAL_FILE_STAT_FIELD_SIZE | G_LOCAL_FILE_STAT_FIELD_BLOCKS | G_LOCAL_FILE_STAT_FIELD_BTIME), flags=2304, pathname=0x555555a23a80 "/home/s/Downloads/testcase", dirfd=-100) at ../glib/gio/glocalfileinfo.h:95
#2  g_local_file_lstat
    (stat_buf=0x7fffffffc6d0, mask_required=(G_LOCAL_FILE_STAT_FIELD_TYPE | G_LOCAL_FILE_STAT_FIELD_MODE | G_LOCAL_FILE_STAT_FIELD_NLINK | G_LOCAL_FILE_STAT_FIELD_UID | G_LOCAL_FILE_STAT_FIELD_GID | G_LOCAL_FILE_STAT_FIELD_MTIME | G_LOCAL_FILE_STAT_FIELD_CTIME | G_LOCAL_FILE_STAT_FIELD_INO | G_LOCAL_FILE_STAT_FIELD_SIZE | G_LOCAL_FILE_STAT_FIELD_BLOCKS), mask=(G_LOCAL_FILE_STAT_FIELD_TYPE | G_LOCAL_FILE_STAT_FIELD_MODE | G_LOCAL_FILE_STAT_FIELD_NLINK | G_LOCAL_FILE_STAT_FIELD_UID | G_LOCAL_FILE_STAT_FIELD_GID | G_LOCAL_FILE_STAT_FIELD_ATIME | G_LOCAL_FILE_STAT_FIELD_MTIME | G_LOCAL_FILE_STAT_FIELD_CTIME | G_LOCAL_FILE_STAT_FIELD_INO | G_LOCAL_FILE_STAT_FIELD_SIZE | G_LOCAL_FILE_STAT_FIELD_BLOCKS | G_LOCAL_FILE_STAT_FIELD_BTIME), path=0x555555a23a80 "/home/s/Downloads/testcase") at ../glib/gio/glocalfileinfo.h:132
#3  _g_local_file_info_get (basename=0x7fffe80023a0 "testcase", path=0x555555a23a80 "/home/s/Downloads/testcase", attribute_matcher=0x555555855ce0, flags=G_FILE_QUERY_INFO_NONE, parent_info=0x7fffffffd830, error=0x0)
    at ../glib/gio/glocalfileinfo.c:1928
#4  0x00007ffff73f09bc in g_local_file_query_info (file=0x555555a217f0, attributes=<optimized out>, flags=G_FILE_QUERY_INFO_NONE, cancellable=<optimized out>, error=0x0) at ../glib/gio/glocalfile.c:1247
#5  0x00007ffff7318f50 in g_file_query_exists (file=file@entry=0x555555a217f0, cancellable=cancellable@entry=0x0) at ../glib/gio/gfile.c:1226
#6  0x000055555557167f in uri_exists (uri=0x555555770640 "file:///home/s/Downloads/testcase/#foo%20(3459070)") at /usr/src/debug/engrampa/engrampa-1.26.1/src/file-utils.c:59
#7  uri_exists (uri=0x555555770640 "file:///home/s/Downloads/testcase/#foo%20(3459070)") at /usr/src/debug/engrampa/engrampa-1.26.1/src/file-utils.c:50
#8  get_alternative_uri (folder=folder@entry=0x5555557576f0 "file:///home/s/Downloads/testcase", name=0x555555a203e6 "#foo") at /usr/src/debug/engrampa/engrampa-1.26.1/src/file-utils.c:1326
#9  0x0000555555573791 in move_here (archive=archive@entry=0x5555558a98e0 [FrArchive]) at /usr/src/debug/engrampa/engrampa-1.26.1/src/fr-archive.c:821
#10 0x0000555555576cf9 in action_performed (command=<optimized out>, action=FR_ACTION_EXTRACTING_FILES, error=0x555555842e10, archive=0x5555558a98e0 [FrArchive]) at /usr/src/debug/engrampa/engrampa-1.26.1/src/fr-archive.c:974
#11 0x00007ffff72766c0 in g_closure_invoke (closure=0x555555980b00, return_value=0x0, n_param_values=3, param_values=0x7fffffffdb70, invocation_hint=0x7fffffffdac0) at ../glib/gobject/gclosure.c:832
#12 0x00007ffff72a4a36 in signal_emit_unlocked_R.isra.0
    (node=node@entry=0x7fffffffdc70, detail=detail@entry=0, instance=instance@entry=0x555555982030, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffdb70)
    at ../glib/gobject/gsignal.c:3980
#13 0x00007ffff7295a42 in signal_emit_valist_unlocked (instance=instance@entry=0x555555982030, signal_id=signal_id@entry=236, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffddd0) at ../glib/gobject/gsignal.c:3612
#14 0x00007ffff7295c77 in g_signal_emit_valist (instance=0x555555982030, signal_id=236, detail=0, var_args=var_args@entry=0x7fffffffddd0) at ../glib/gobject/gsignal.c:3355
#15 0x00007ffff7295d34 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../glib/gobject/gsignal.c:3675
#16 0x00007ffff72766c0 in g_closure_invoke (closure=0x555555761270, return_value=0x0, n_param_values=2, param_values=0x7fffffffe080, invocation_hint=0x7fffffffdfd0) at ../glib/gobject/gclosure.c:832
#17 0x00007ffff72a4a36 in signal_emit_unlocked_R.isra.0
    (node=node@entry=0x7fffffffe170, detail=detail@entry=0, instance=instance@entry=0x555555898150, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffe080)
    at ../glib/gobject/gsignal.c:3980
#18 0x00007ffff7295a42 in signal_emit_valist_unlocked (instance=instance@entry=0x555555898150, signal_id=signal_id@entry=272, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffe2d0) at ../glib/gobject/gsignal.c:3612
#19 0x00007ffff7295c77 in g_signal_emit_valist (instance=0x555555898150, signal_id=272, detail=0, var_args=var_args@entry=0x7fffffffe2d0) at ../glib/gobject/gsignal.c:3355
#20 0x00007ffff7295d34 in g_signal_emit (instance=instance@entry=0x555555898150, signal_id=<optimized out>, detail=detail@entry=0) at ../glib/gobject/gsignal.c:3675
#21 0x000055555558ae36 in check_child (data=0x555555898150, data@entry=<error reading variable: value has been optimized out>) at /usr/src/debug/engrampa/engrampa-1.26.1/src/fr-process.c:986
#22 0x00007ffff71713ee in g_timeout_dispatch (source=0x555555a2cab0, callback=<optimized out>, user_data=<optimized out>) at ../glib/glib/gmain.c:5121
#23 0x00007ffff716ff69 in g_main_dispatch (context=0x5555556499d0) at ../glib/glib/gmain.c:3476
#24 0x00007ffff71ce327 in g_main_context_dispatch_unlocked (context=0x5555556499d0) at ../glib/glib/gmain.c:4284
#25 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x5555556499d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4349
#26 0x00007ffff716e162 in g_main_context_iteration (context=context@entry=0x5555556499d0, may_block=may_block@entry=1) at ../glib/glib/gmain.c:4414
#27 0x00007ffff73a3b16 in g_application_run (application=application@entry=0x55555572d4d0 [GtkApplication], argc=<optimized out>, argv=0x7fffffffe768) at ../glib/gio/gapplication.c:2577
#28 0x0000555555567269 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/engrampa/engrampa-1.26.1/src/main.c:357
```

#### MATE general version
extra/mate-desktop 1.26.2-1 (mate)

#### Package version
extra/engrampa 1.26.1-1 (mate-extra)

#### Linux Distribution
Arch

#### Link to bugreport of your Distribution (requirement)
N/A

### PR DESCRIPTION
**Pull request by zhuyaliang**
Fix #501

### CODE REVIEW

**Comment by zhuyaliang** [comment]
@cwendling Do you accept the repair method？

**Comment by cwendling** [comment]
Does this actually fix the issue, even for a file named `foo#bar`?  Can't you use [`g_uri_escape_string()`](https://docs.gtk.org/glib/type_func.Uri.escape_string.html) which should be more robust?

**Comment by zhuyaliang** [comment]
@cwendling I confirm that the issue has been fixed. The problem only occurs when the first character in the string is a special character，I use ```g_uri_escape_string (name, G_URI_RESERVED_CHARS_GENERIC_DELIMITERS, FALSE)``` failed to solve the issue

**Comment by zhuyaliang** [comment]
Can you tell me the correct usage of  ```g_uri_escape string```?

**Comment by zhuyaliang** [comment]
> Does this actually fix the issue, even for a file named foo#bar?

It is indeed possible to handle this format of file, although it does not block, the result is abnormal

**Comment by cwendling** [comment]
`g_uri_escape string(name, NULL, TRUE)`
Passing `G_URI_RESERVED_CHARS_GENERIC_DELIMITERS` as `reserved_chars_allowed` defeats the purpose, as it will *not* escape the characters that are the most important to escape :)

**Comment by cwendling** [comment]
Looks generally better (and possibly OK).

This should be tested with all kind of file names including `%`, `?` and `#` in them, if possible in all possible usage scenario of these functions, yet I'm not sure yet which code paths lead to calling of those functions.

**Review by raveit65 — APPROVED** [review]
I didn't find time for testing but it LGTM.

**Comment by zhuyaliang** [comment]
@cwendling Can we merge?

**Review by cwendling — CHANGES_REQUESTED** [review]
This doesn't do what it should: sure the hang is gone, but if I extract the sample it crates directory `%23foo`, not the expected `#foo` one.

**Review by cwendling — CHANGES_REQUESTED** [review]
Creates wrong directory names for `--extract-here` with URI special characters in.  Can be tested with the sample from #501 (or with [engrampa-501-test.zip](https://github.com/mate-desktop/engrampa/files/14025695/engrampa-501-test.zip) which has more reserved characters for testing yet still reproduces the bug)

**Comment by cwendling** [comment]
I actually took the liberty of pushing my suggested changes to the branch so others can test easier; feel free to revert to 10b0bbb9e76c24baaa3ae8639fa80dba8a6fba75 and tell me if you don't like me doing this.

**Comment by cwendling** [comment]
…and rebased on top of 40fbfca42d7166c05e55797e73431ef7de46173b to hopefully get a green build :)

**Review by raveit65 — APPROVED** [review]
LGTM,
runs fine.

**Pull request merged**
