### PR TITLE
Only open debian packages with dpkg

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by lukefromdc** [comment]
Am I correct in assuming this is not supposed to.remove Engrampa's ability to open .deb
packages for reading? That's an ability I use all the time and oppose removing.

**Comment by rbuj** [comment]
ar command can't open old deb files:

Captura de pantalla a 2019-09-15 19-17-44

dpkg can open all deb files:

Captura de pantalla a 2019-09-15 19-14-53

**Comment by sc0w** [comment]
@rbuj can you attach non working file with ar ?

I can open the file you mentioned before witn engrampa 1.22.2

http://snapshot.debian.org/package/lilo/16-0/

http://snapshot.debian.org/archive/debian-archive/20090802T004153Z/debian/dists/Debian-0.93R6/binary/admin/lilo-16-0.deb

**Comment by rbuj** [comment]
> I can open the file you mentioned before witn engrampa 1.22.2
```shell
$ wget -q http://snapshot.debian.org/archive/debian-archive/20090802T004153Z/debian/dists/Debian-0.93R6/binary/admin/lilo-16-0.deb
```
### ar
```shell
$ ar tv lilo-16-0.deb 
ar: lilo-16-0.deb: file format not recognized
```
### dpkg
```shell
$ LANG=C dpkg-deb -I lilo-16-0.deb 
 old debian package, version 0.939000.
 size 105980 bytes: control archive=1140, main archive=104826.
     166 bytes,     5 lines      control              
    1773 bytes,    70 lines   *  postinst             #!
 PACKAGE: lilo
 DESCRIPTION: LInux LOader - Loads Linux from the hard disk without a floppy.
 MAINTAINER: Bruce Perens <Bruce@Pixar.com>
 VERSION: 16
 PACKAGE_REVISION: 0
$ LANG=C dpkg-deb -c lilo-16-0.deb 
drwxr-xr-x root/root         0 1995-07-09 22:01 ./
drwxr-xr-x root/root         0 1995-07-09 22:01 sbin/
-rwxr-xr-x root/root     40960 1995-07-09 22:01 sbin/lilo
drwxr-xr-x root/root         0 1995-07-09 22:00 etc/
drwxr-xr-x root/root         0 1995-07-09 22:01 boot/
-rw-r--r-- root/root      3336 1995-07-09 22:01 boot/boot.b
-rw-r--r-- root/root       200 1995-07-09 22:01 boot/any_b.b
-rw-r--r-- root/root       200 1995-07-09 22:01 boot/any_d.b
-rw-r--r-- root/root        88 1995-07-09 22:01 boot/chain.b
-rw-r--r-- root/root       140 1995-07-09 22:01 boot/os2_d.b
drwxr-xr-x root/root         0 1995-07-09 22:01 usr/
drwxr-xr-x root/root         0 1995-07-09 22:01 usr/doc/
drwxr-xr-x root/root         0 1995-07-09 22:01 usr/doc/copyright/
-rw-r--r-- root/root      1031 1995-07-09 22:01 usr/doc/copyright/lilo
drwxr-xr-x root/root         0 1995-07-09 22:01 usr/doc/lilo/
-rw-r--r-- root/root       428 1995-02-13 22:34 usr/doc/lilo/bootloader.fig.gz
-rw-r--r-- root/root       530 1995-02-26 02:10 usr/doc/lilo/bootloader.tex.gz
-rw-r--r-- root/root       465 1993-04-11 20:01 usr/doc/lilo/fullpage.sty.gz
-rw-r--r-- root/root       380 1995-02-13 22:36 usr/doc/lilo/image.fig.gz
-rw-r--r-- root/root       478 1995-02-26 02:10 usr/doc/lilo/image.tex.gz
-rw-r--r-- root/root       321 1995-02-13 22:35 usr/doc/lilo/map.fig.gz
-rw-r--r-- root/root       407 1995-02-13 22:39 usr/doc/lilo/other.fig.gz
-rw-r--r-- root/root       488 1995-02-26 02:10 usr/doc/lilo/other.tex.gz
-rw-r--r-- root/root       376 1993-09-27 20:26 usr/doc/lilo/parameter.fig.gz
-rw-r--r-- root/root       412 1995-01-26 23:23 usr/doc/lilo/parameter.tex.gz
-rwxr-xr-x root/root       240 1994-10-16 16:09 usr/doc/lilo/rlatex.gz
-rwxr-xr-x root/root      3776 1994-10-21 20:30 usr/doc/lilo/t2a.pl.gz
-rw-r--r-- root/root      4546 1995-02-26 04:05 usr/doc/lilo/tech.tex.gz
-rw-r--r-- root/root     35075 1995-02-26 04:04 usr/doc/lilo/user.tex.gz
-rw-r--r-- root/root       332 1994-10-21 21:22 usr/doc/lilo/Makefile.gz
-rw-r--r-- root/root      1049 1995-02-10 15:11 usr/doc/lilo/README.gz
-rw-r--r-- root/root       393 1995-02-26 02:10 usr/doc/lilo/map.tex.gz
-rw-r--r-- root/root     31724 1995-02-26 04:11 usr/doc/lilo/READ_ME_FIRST.gz
drwxr-xr-x root/root         0 1995-07-09 22:01 usr/doc/examples/
drwxr-xr-x root/root         0 1995-07-09 22:01 usr/doc/examples/lilo/
-rw-r--r-- root/root       324 1995-07-09 22:01 usr/doc/examples/lilo/lilo.conf
```

**Comment by sc0w** [comment]
yes, but engrampa can open the file without this PR, I can't see the error dialog

seems it is already handled with dpkg

**Comment by rbuj** [comment]
> yes, but engrampa can open the file without this PR, I can't see the error dialog

dpkg is installed by default on Debian/Ubuntu, not in Fedora/Mageia/Arch/...

**Comment by sc0w** [comment]
yes, but the file mentioned is working if the user just install `dpkg` without this PR, it is not needed to remove the ability to load `deb` files with `ar` in my opinion.

**Comment by lukefromdc** [comment]
In other words, ar for Debian is used only as a fallback that can open newer but not all Debian archives? In that case the correct fix is to ensure dpkg is always used for .deb files if present, but continue to fall back to ar if it is not. Screenshots above show a failure of engrampa to open an older .deb file without this, was that with or without dpkg installed on the system?

**Comment by rbuj** [comment]
The ar command is never used for opening .deb files for the distros that ship their packages with .deb, since dpkg is always installed on these systems. On GNU/Linux systems that don't include dpkg by default, engrampa uses the ar command, but the user don't know that have to install dpkg to handle properly .deb files.

The dpkg command is not available on [openindiana](https://pkg.openindiana.org/hipster/en/search.shtml?token=dpkg&action=Search), in such case we can keep the command compatibility:
```patch
--- a/src/fr-command-ar.c
+++ b/src/fr-command-ar.c
@@ -277,7 +277,11 @@ fr_command_ar_handle_error (FrCommand   *comm,
 }
 
 
-const char *ar_mime_type[] = { "application/x-ar", NULL };
+const char *ar_mime_type[] = { "application/x-ar",
+#if defined(__sun) && defined(__SVR4)
+                               "application/vnd.debian.binary-package",
+#endif
+                               NULL };
 
 
 static const char **
@@ -296,8 +300,15 @@ fr_command_ar_get_capabilities (FrCommand  *comm,
 
        capabilities = FR_COMMAND_CAN_ARCHIVE_MANY_FILES;
        if (is_program_available ("ar", check_command)) {
+#if defined(__sun) && defined(__SVR4)
+               if (is_mime_type (mime_type, "application/vnd.debian.binary-package"))
+                       capabilities |= FR_COMMAND_CAN_READ;
+               else if (is_mime_type (mime_type, "application/x-ar"))
+                       capabilities |= FR_COMMAND_CAN_READ_WRITE;
+#else
                if (is_mime_type (mime_type, "application/x-ar"))
                        capabilities |= FR_COMMAND_CAN_READ_WRITE;
+#endif
        }
 
        return capabilities;
```
dpkg is [available](https://pkgs.org/download/dpkg) for most GNU/Linux distributions and *BSD systems.

**Comment by sc0w** [comment]
`ar` can open `.deb` files, there is no reason to remove this feature, `dpkg` has priority over `ar`, the user can decide

`engrampa` works with the same behavior with other formats, for example `unar` and `rar` can open `rar` files, `unzip` and `7z` can open `zip` files, etc. etc.

**Pull request closed without merging**
