### PR TITLE
Enable Travis CI

### PR DESCRIPTION
**Pull request by yetist**
@raveit65 

Can you enable travis for this repo?

### CODE REVIEW

**Comment by raveit65** [comment]
@yetist 
It's enabled.

**Comment by raveit65** [comment]
Can we remove `only travis` branch before merging?
I am still wondering why we have only one check here?

**Comment by yetist** [comment]
I just finished the local test and I still need to test it online, but I can't test it online before you enable it on travis website, so I added WIP to the title and hope that dont merge. 
Maybe we need this tool to help us: https://github.com/marketplace/wip

BTW, you can enable more repos on travis website.

**Comment by yetist** [comment]
All ready now.

**Comment by raveit65** [comment]
> BTW, you can enable more repos on travis website.

Ok, i will do.

**Comment by raveit65** [comment]
All repos are enabled at travis, except legacy packages.

**Pull request merged**
