### PR TITLE
Fix: compress rar split into volumes

### LINKED ISSUE #127: No output file from archiver with parted rar/7z archives over engrampa
My system:
Linux Mint 17.3 Rosa 64-bit
Kernel Linux 3.19.0-32-generic x86_64
MATE 1.12.0

Packing over the terminal works fine.
With engrampa (right mouse button), it works only with not parted archives (single file).
If i want to create a parted archive over engrampa, the process works and create a temp folder with the compressed output files.
After processing, the created temp folder will be deleted.
That's so since 17.1. With 17.0 it works correctly.

### PR DESCRIPTION
**Pull request by sc0w**
Fixes #127

### CODE REVIEW

**Comment by raveit65** [comment]
As rar is non-free i can't really test it as i don`t have rar.

**Comment by raveit65** [comment]
I found a trial version somewhere.
It works well now, nice work.

**Comment by raveit65** [comment]
Btw. you ask for more reviewer if you like ;-)

**Comment by sc0w** [comment]
thanks for your quick tests

next step: .cbr

**Pull request merged**
