### PR TITLE
Initialization discards ‘const’ qualifier from pointer target type

### PR DESCRIPTION
**Pull request by rbuj**
Remove 317 warnings [-Wdiscarded-qualifiers].

### CODE REVIEW

**Comment by raveit65** [comment]
Hmm, i don't get this warnings in master.
Compiled with edited configure.ac
```
-WARN_CFLAGS="-Wall -Wcast-align -Wtype-limits -Wclobbered -Wempty-body -Wignored-qualifiers"
+WARN_CFLAGS="-Wdiscarded-qualifiers"
```
`/autogen.sh && make &> result.txt`
But `grep Wdiscarded-qualifiers result.txt` doesn't show me those warnings.
Do i miss something?

**Comment by rbuj** [comment]
```bash
#!/bin/bash
CFLAGS="-g -O -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wendif-labels -Wformat=2 -Winit-self -Wswitch-enum -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-align -Wwrite-strings -Wjump-misses-init -Wlogical-op -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Wnested-externs -Wundef -Wformat-security" ./autogen.sh --prefix=/usr
make clean &> /dev/null
make 2> report.txt
for warning in $(grep warning report.txt | grep -Po '\[\-W.*\]' | sed 's/[][]//g' | sort -u)
do
 type=${warning#"-W"}
 num=$(echo "grep $type report.txt | wc -l" | sh)
 echo "$warning $num"
done
```
Before:
```

-Wcast-function-type 65
-Wdeprecated-declarations 58
-Wdiscarded-qualifiers 351 <--
-Wformat-nonliteral 1
-Wmissing-field-initializers 2
-Wmissing-prototypes 4
-Wsign-compare 1
-Wswitch-enum 77
-Wundef 2
-Wunused-function 1
-Wunused-parameter 495
```
After:
```
-Wcast-function-type 65
-Wdeprecated-declarations 58
-Wdiscarded-qualifiers 34 <-- remove 317 warnings
-Wformat-nonliteral 1
-Wmissing-field-initializers 2
-Wmissing-prototypes 4
-Wsign-compare 1
-Wswitch-enum 77
-Wundef 2
-Wunused-function 1
-Wunused-parameter 495
```

**Comment by raveit65** [comment]
Ok,  i see the warnings with using
```
WARN_CFLAGS="-Wwrite-strings"
```
in `configure.ac`. but docs tells nothing why the warnings are named with `Wdiscarded-qualifiers`
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

**Comment by lukefromdc** [comment]
Passes all the checks, so will merge

**Pull request merged**
