### PR TITLE
ar: fix filename in file list

### PR DESCRIPTION
**Pull request by rbuj**
Test:
```
$ touch -d "2021-02-01" 2021-02-01.txt
$ touch -d "2021-02-10" 2021-02-10.txt
$ ar r test.ar 2021-02-01.txt 2021-02-10.txt
$ engrampa test.ar
```

### CODE REVIEW

**Comment by thesquash** [comment]
I approve of this instead, if that's what floats your boat.

**Comment by raveit65** [comment]
> I approve of this instead, if that's what floats your boat.

Does this float your boat?

**Review by raveit65 — APPROVED** [review]
LGTM,
does what it promise.

**Comment by raveit65** [comment]
I guess this is a bugfix for stable branch and it will obsolete https://github.com/mate-desktop/engrampa/pull/429 ?

**Comment by thesquash** [comment]
Yes, #429 is obsolete and can be closed.

**Comment by raveit65** [comment]
@rbuj 
I guess this is a bugfix for stable branch?

**Comment by rbuj** [comment]
@raveit65 Yes, it has been cherry-picked to the stable branch.

**Pull request merged**
