### PR TITLE
Fix icon missing when compressing files with the right mouse button

### PR DESCRIPTION
**Pull request by zhuyaliang**
Fix icon missing when compressing files with the right mouse button
#412

### CODE REVIEW

**Comment by zhuyaliang** [comment]
@lukefromdc Please verify that the problem is resolved

**Review by lukefromdc — COMMENTED** [review]
Just tested this, still get default file (NOT default package) icon for compressing from caja to a .gz file both in my own  theme and in menta (tested both in case my icon theme was the issue)

**Comment by zhuyaliang** [comment]
@lukefromdc Please confirm whether there is a ```package-x-generic``` icon under your current theme,I confirm that I have fixed this issue

**Comment by lukefromdc** [comment]
Yes there is, and it is used by caja with many package types not otherwise references. 
Filename is
/usr/share/icons/UbuntuStudio_Legacy/mimes/scalable/package-x-generic.svg

Note that this is an svg icon, though I had the same issue in Menta. There could be some
issue specific to my install of course so I won't oppose a merge over this

**Comment by zhuyaliang** [comment]
```
mate@mouse engrampa]$ find /usr/share/icons/ | grep package-x-generic
/usr/share/icons/Adwaita/scalable/mimetypes/package-x-generic-symbolic.svg
/usr/share/icons/Adwaita/32x32/mimetypes/package-x-generic-symbolic.symbolic.png
/usr/share/icons/Adwaita/32x32/mimetypes/package-x-generic.png
/usr/share/icons/Adwaita/24x24/mimetypes/package-x-generic-symbolic.symbolic.png
/usr/share/icons/Adwaita/24x24/mimetypes/package-x-generic.png
/usr/share/icons/Adwaita/64x64/mimetypes/package-x-generic-symbolic.symbolic.png
/usr/share/icons/Adwaita/48x48/mimetypes/package-x-generic-symbolic.symbolic.png
/usr/share/icons/Adwaita/48x48/mimetypes/package-x-generic.png
/usr/share/icons/Adwaita/16x16/mimetypes/package-x-generic-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/mimetypes/package-x-generic.png
/usr/share/icons/Adwaita/512x512/mimetypes/package-x-generic.png
/usr/share/icons/Adwaita/96x96/mimetypes/package-x-generic-symbolic.symbolic.png
/usr/share/icons/Adwaita/22x22/mimetypes/package-x-generic.png
/usr/share/icons/matefaenza/mimetypes/16/package-x-generic.png
/usr/share/icons/matefaenza/mimetypes/scalable/package-x-generic.svg
/usr/share/icons/matefaenza/mimetypes/24/package-x-generic.png
/usr/share/icons/matefaenza/mimetypes/64/package-x-generic.png
/usr/share/icons/matefaenza/mimetypes/22/package-x-generic.png
/usr/share/icons/matefaenza/mimetypes/32/package-x-generic.png
/usr/share/icons/matefaenza/mimetypes/96/package-x-generic.png
/usr/share/icons/matefaenza/mimetypes/48/package-x-generic.png
/usr/share/icons/ContrastHigh/scalable/mimetypes/package-x-generic.svg
/usr/share/icons/ContrastHigh/32x32/mimetypes/package-x-generic.png
/usr/share/icons/ContrastHigh/24x24/mimetypes/package-x-generic.png
/usr/share/icons/ContrastHigh/48x48/mimetypes/package-x-generic.png
/usr/share/icons/ContrastHigh/16x16/mimetypes/package-x-generic.png
/usr/share/icons/ContrastHigh/256x256/mimetypes/package-x-generic.png
/usr/share/icons/ContrastHigh/22x22/mimetypes/package-x-generic.png
/usr/share/icons/mate/scalable/mimetypes/package-x-generic-symbolic.svg
/usr/share/icons/mate/32x32/mimetypes/package-x-generic.png
/usr/share/icons/mate/24x24/mimetypes/package-x-generic.png
/usr/share/icons/mate/48x48/mimetypes/package-x-generic.png
/usr/share/icons/mate/16x16/mimetypes/package-x-generic.png
/usr/share/icons/mate/256x256/mimetypes/package-x-generic.png
/usr/share/icons/mate/22x22/mimetypes/package-x-generic.png
/usr/share/icons/HighContrast/scalable/mimetypes/package-x-generic.svg
/usr/share/icons/HighContrast/32x32/mimetypes/package-x-generic.png
/usr/share/icons/HighContrast/24x24/mimetypes/package-x-generic.png
/usr/share/icons/HighContrast/48x48/mimetypes/package-x-generic.png
/usr/share/icons/HighContrast/16x16/mimetypes/package-x-generic.png
/usr/share/icons/HighContrast/256x256/mimetypes/package-x-generic.png
/usr/share/icons/HighContrast/22x22/mimetypes/package-x-generic.png
```

```
[mate@mouse engrampa]$ pacman -Ql mate-icon-theme | grep package-x-generic
mate-icon-theme /usr/share/icons/mate/16x16/mimetypes/package-x-generic.png
mate-icon-theme /usr/share/icons/mate/22x22/mimetypes/package-x-generic.png
mate-icon-theme /usr/share/icons/mate/24x24/mimetypes/package-x-generic.png
mate-icon-theme /usr/share/icons/mate/256x256/mimetypes/package-x-generic.png
mate-icon-theme /usr/share/icons/mate/32x32/mimetypes/package-x-generic.png
mate-icon-theme /usr/share/icons/mate/48x48/mimetypes/package-x-generic.png
mate-icon-theme /usr/share/icons/mate/scalable/mimetypes/package-x-generic-symbolic.svg
```
Please install this icon

**Comment by lukefromdc** [comment]
Already installed on my system and the icon cache is up to date

**Comment by lukefromdc** [comment]
Also note someone else found this not changing the issue:
https://github.com/mate-desktop/engrampa/issues/412#issuecomment-1484033838

**Comment by zhuyaliang** [comment]
@lukefromdc Does the ```application-x-generic``` icon exist in your system theme

**Comment by lukefromdc** [comment]
Pretty sure it doea but on the road now and cannot chexk

**Comment by zhuyaliang** [comment]
application-x-generic
So I think it's normal

**Comment by lukefromdc** [comment]
That's a file icon not a package icon, if this is the default it may be the source of the problem

**Comment by zhuyaliang** [comment]
This is easy to verify. Compile this code, and then run it to obtain the default icon for ```. gz```
```
gcc `pkg-config --cflags --libs gtk+-3.0` test.c -o test
```
```
#include <gtk/gtk.h>

int main (int argc, char *argv[])
{
    gtk_init (&argc, &argv);

    g_print ("icon_name = %s\r\n", g_content_type_get_generic_icon_name ("application/x-gzip"));

    return 0;
}
```

**Comment by lukefromdc** [comment]
I can't get this to find gtk with this code, getting this error:
```

luke@ubuntu:~/Desktop$ gcc `pkg-config --cflags --libs gtk+-3.0` test.c -o test
/usr/bin/ld: /tmp/ccUXF1Be.o: in function `main':
test.c:(.text+0x1e): undefined reference to `gtk_init'
/usr/bin/ld: test.c:(.text+0x2d): undefined reference to `g_content_type_get_generic_icon_name'
/usr/bin/ld: test.c:(.text+0x44): undefined reference to `g_print'
collect2: error: ld returned 1 exit status
luke@ubuntu:~/Desktop$ 
```

**Comment by zhuyaliang** [comment]
@lukefromdc Please check if ```gtk+-3.0.pc``` exists
```
pkg-config --list-all | grep gtk+-3.0
```

**Comment by lukefromdc** [comment]
That yields 

```
 pkg-config --list-all | grep gtk+-3.0
gtk+-3.0                       GTK+ - GTK+ Graphical UI Library
```
and if that file did not exist I probably could not build MATE packages (all of mine are local builds)

**Comment by zhuyaliang** [comment]
Run ```echo 'pkg config -- cflags -- libs gtk+- 3.0'``` to view the output results
```
[mate@mouse tmp]$ echo `pkg-config --cflags --libs gtk+-3.0`
-I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -pthread -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
[mate@mouse tmp]$ 
[mate@mouse tmp]$ gcc -o test test.c  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -pthread -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
[mate@mouse tmp]$  
```

**Comment by lukefromdc** [comment]
That yields 
`pkg config -- cflags -- libs gtk+- 3.0`

**Comment by zhuyaliang** [comment]
@lukefromdc 
Should be ```echo `pkg-config --cflags --libs gtk+-3.0` ```, missing the '-' character

**Comment by lukefromdc** [comment]
That yields

```
$ echo `pkg-config --cflags --libs gtk+-3.0`
-I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -pthread -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0

```

**Comment by zhuyaliang** [comment]
@lukefromdc 
Try compiling like this
```
gcc -o test test.c -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -pthread -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0

```

**Comment by lukefromdc** [comment]
That worked, and running the binary gave this output:
`icon_name = application-x-generic`

**Comment by zhuyaliang** [comment]
@lukefromdc 
This is not a problem with ```engramma```, it doesn't seem to work here
```
<generic-icon name="package-x-generic"/>

<glob pattern="*.gz"/>

<alias type="application/x-gzip"/>
```
The icon of ```x-gzip``` is parsed into ```application-x-generic```

**Comment by lukefromdc** [comment]
OK, that's a problem needing to be fixed elsewhere. The right icon is used in caja and other file managers, possibly by being called under a diffreent name?

**Comment by lukefromdc** [comment]
Not sure what we should do with this as it has no effect on the original problem as it is the wrong icon coming up when called, not a non-existant icon name being called.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/engrampa/issues/412 edited to reflect this

**Comment by lukefromdc** [comment]
If Engrampa's not the issue we might have to close the bug report and this as well unless it fixes another problem, and find the underlying issue and open a new report there no doubt in an underlying library

**Comment by zhuyaliang** [comment]
@lukefromdc Please test again, I updated the code

**Pull request merged**
