### PR TITLE
autoconf: get zstd mime type using libmagic if enabled

### PR DESCRIPTION
**Pull request by rbuj**
Test:
```shell
$ sudo update-desktop-database /usr/share/applications
$ base64 /dev/urandom | head -c 1048576 > test.txt
$ zstd test.txt
$ engrampa test.txt.zst
```

### CODE REVIEW

**Comment by monsta** [comment]
Since file/libmagic versions before 5.38 reported the wrong type, maybe just rely on 5.38 and use `application/zstd` always?

**Comment by rbuj** [comment]
Some distros don't ship file 5.38 like Fedora 30 (file 5.36) or Fedora 31 (file 5.37).

```shell
[robert@localhost libmatekbd]$ cat /etc/redhat-release 
Fedora release 30 (Thirty)
[robert@localhost libmatekbd]$ file -v
file-5.36
magic file from /etc/magic:/usr/share/misc/magic
```
[RPM Find Query](https://rpmfind.net/linux/rpm2html/search.php?query=file&submit=Search+...&system=fedora&arch=x86_64)

**Comment by raveit65** [comment]
Can you add a note in configure.ac please, that this fix can be removed with file-5.38?

**Comment by rbuj** [comment]
@raveit65 done

**Comment by monsta** [comment]
```
$ grep MAGIC_VERSION /usr/include/magic.h 
#define MAGIC_VERSION		530	/* This implementation */
```
Maybe we can utilize this somehow?

**Comment by monsta** [comment]
Weird, in my Debian Testing there's no zstd type in `/usr/share/mime` at all. Running `update-mime-database` had no effect. So Caja says `application/octet-stream` in the archive properties.

**Comment by Piraty** [comment]
how about handling libmagic's returned mime types at runtime instead?
```
else if (is_mime_type (comm->mime_type, "application/x-zstd") || is_mime_type (comm->mime_type, "application/zstd") ) {
```

**Comment by Piraty** [comment]
That commit broke crosscompilation as well, as you're using the target compiler

**Pull request merged**
