### PR TITLE
add hability to show folders (F9) in "View All Files"

### PR DESCRIPTION
**Pull request by sc0w**
This is a good feature in combination with the PR https://github.com/mate-desktop/engrampa/pull/174

### CODE REVIEW

**Comment by lukefromdc** [comment]
I built this branch directly from your repo, and just now realized this branch did not apply the previous commit to hide folders https://github.com/mate-desktop/engrampa/pull/174

**Comment by raveit65** [comment]
In this branch here, do 'git rebase sc0w-hidefolders'. After that you will see the 'hide folder' comment here.
```
[rave@mother engrampa]$ git log
commit 3c8fe13077c938736459e71040b8965dfcfa8117
Author: ZenWalker <scow@riseup.net>
Date:   Sat May 6 01:38:14 2017 +0200

    add ability to show folders (F9) in "View All Files"

commit 988b01c1492930741f2a61eb89781df495fbf0f6
Author: ZenWalker <scow@riseup.net>
Date:   Thu May 4 16:35:25 2017 +0200

    hide folders in "View All Files"
    
    Fixes #172

commit dff9db3296b4d0e7711271f429a70c7340a68e85
Author: ZenWalker <scow@riseup.net>
Date:   Tue May 2 20:15:58 2017 +0200

    Fix: Wrong behavior of Skip button in Replace file dialog
    
    based in file-roller commit:
    https://git.gnome.org/browse/file-roller/commit/?id=fe71357aa128d029b6ca4a9493b8a408c8aaf017
    
    Fixes #161

commit dfc3401d081a43fbbc97852bb60ecefd7759cd4c
```

**Comment by raveit65** [comment]
Hmm, i am not sure about. I am using both commits.
I can toggle the sidebar on/off in 'view all files', but what is the benefit?.
On the right side i see always all files, it doesn't matter if i select a sub folder at the sidebar or not.
And if i select one folder in sidebar and choose 'delete selected files', it seems that only the folder is deleted.
But i do not see the reason why i should enable the sidebar here.

**Comment by sc0w** [comment]
My intention with this PR is to come back the ability to show folders in "view all files" (in the side panel, in this case), only to see the folders structure quickly

Anyway, I don't like the behavior of this PR in some situations, so I close this (by the moment)

**Pull request closed without merging**
