### PR TITLE
zstd: support both old and new mime type

### PR DESCRIPTION
**Pull request by sgn**
As of it's now, we're supporting zstd {,de}compression with specific
mime type that was reported by libmagic as configure time. Thus, the
built binaries is not correct after upgrading file-devel after
configure. In addition, this configure's time hard-coded value prevent
our users from partial upgrade.

Let's accept both mime types reported by both old and new file-devel.
For the mapping between file extensions and mime types, let's choose the
new mime value.

---

Linked: https://github.com/void-linux/void-packages/pull/27171

### CODE REVIEW

**Comment by rbuj** [comment]
There is still an occurrence of `ZSTD_MIME_TYPE` in data/engrampa.desktop.in.in file:
```
$ git grep ZSTD_MIME_TYPE
```

**Comment by rbuj** [comment]
Anyway, I think we can use the new value for the mime type and discard the old one, since file was published last year in late December.

ftp://ftp.astron.com/pub/file/

**Comment by sgn** [comment]
> There is still an occurrence of `ZSTD_MIME_TYPE` in data/engrampa.desktop.in.in file:
> 
> ```
> $ git grep ZSTD_MIME_TYPE
> ```

Ah yes, I was applied the patch for 1.24.1 but I forgot to check the rejection :(


> Anyway, I think we can use the new value for the mime type and discard the old one, since file was published last year in late December.
> 
> ftp://ftp.astron.com/pub/file/

My main motivation was about allowing partial upgrading. However, simply use the new value is fine, too.

**Comment by rbuj** [comment]
We can use only the new mime type, and add a check to require `libmagic >= 5.38` in configure.ac, since libmagic.pc was introduced on https://github.com/file/file/commit/2f8ae1e99e89cde6ef6b6d2b5b01480637809aba

It should be reviewed by other @mate-desktop/core-team members.

Test:
```
$ pkg-config --exists --print-errors "libmagic >= 5.38"
$ cat /usr/lib64/pkgconfig/libmagic.pc
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: libmagic
Description: Magic number recognition library
Version: 5.39
Libs: -L${libdir} -lmagic
Libs.private: -lz 
```
Related #353

**Comment by rbuj** [comment]
We can also add zstd mime type in local `magic_ids` ( ! ENABLE_MAGIC)
```diff
diff --git a/mate-submodules b/mate-submodules
index 54fff1b..580a612 160000
--- a/mate-submodules
+++ b/mate-submodules
@@ -1 +1 @@
-Subproject commit 54fff1b15efa5c88d4bb19ebbae9476a03f9db32
+Subproject commit 580a612e236053bddf552cc6819e49c508de4aab
diff --git a/src/fr-archive.c b/src/fr-archive.c
index 029d6fb..f18a4a6 100644
--- a/src/fr-archive.c
+++ b/src/fr-archive.c
@@ -569,6 +569,7 @@ get_mime_type_from_magic_numbers (GFile *file)
                { 0,  4, "LRZI",                                 "application/x-lrzip"         },
                { 0,  2, "\x1f\x9d",                             "application/x-compress"      }, /* using Lempel-Ziv-Welch   algorithm */
                { 0,  2, "\x1f\xa0",                             "application/x-compress"      }, /* using Lempel-Ziv-Huffman algorithm */
+               { 0,  4, "\x28\xB5\x2F\xFD",                     "application/zstd"            },
        };
 
        char   buffer[32];
```
To get the mime type for a ztd archive:
- 1st search method (`get_mime_type_from_filename`): it looks for the extension on the `file_ext_type` array (fr-init.c), it makes no sense to add more than one ".zst" file extension as it only takes into account the first one on the array.
- 2nd search method (`get_mime_type_from_filename`): `g_file_query_info` from gio. Test FILENAME without ".zst" file extension.
```
$ gio info --attributes=standard::content-type  FILENAME
<cut>
  standard::content-type: application/zstd
```
- 3rd search method (get_mime_type_from_magic_numbers): libmagic (ENABLE_MAGIC)

```C
        mime_type = get_mime_type_from_filename (archive->local_copy);
        if (! create_command_to_load_archive (archive, mime_type)) {
                mime_type = get_mime_type_from_content (archive->local_copy);
                if (! create_command_to_load_archive (archive, mime_type)) {
                        mime_type = get_mime_type_from_magic_numbers (archive->local_copy);
                        if (! create_command_to_load_archive (archive, mime_type)) {
                                archive->command = old_command;
                                archive->content_type = mime_type;
                                fr_archive_action_completed (archive,
                                                             FR_ACTION_LOADING_ARCHIVE,
                                                             FR_PROC_ERROR_UNSUPPORTED_FORMAT,
                                                             _("Archive type not supported."));
                                return;
                        }
                }
        }
```

**Comment by lukefromdc** [comment]
This  cannot now be configured if applied against current master due to the change in translation systems. This error results:
```

caja/Makefile.am:26: error: USE_NLS does not appear in AM_CONDITIONAL
caja/Makefile.am: installing './depcomp'
data/Makefile.am:8: error: USE_NLS does not appear in AM_CONDITIONAL
data/Makefile.am:14: error: ENABLE_PACKAGEKIT does not appear in AM_CONDITIONAL
data/Makefile.am:30: error: USE_NLS does not appear in AM_CONDITIONAL
help/Makefile.am:13: error: USE_NLS does not appear in AM_CONDITIONAL
autoreconf: error: automake failed with exit status: 1

```

Test was to drop these files into a just built directory from current master, then try to reconfigure and rebuild

**Comment by sgn** [comment]
> This cannot now be configured if applied against current master due to the change in translation systems. This error results:
> 
> ```
> 
> caja/Makefile.am:26: error: USE_NLS does not appear in AM_CONDITIONAL
> caja/Makefile.am: installing './depcomp'
> data/Makefile.am:8: error: USE_NLS does not appear in AM_CONDITIONAL
> data/Makefile.am:14: error: ENABLE_PACKAGEKIT does not appear in AM_CONDITIONAL
> data/Makefile.am:30: error: USE_NLS does not appear in AM_CONDITIONAL
> help/Makefile.am:13: error: USE_NLS does not appear in AM_CONDITIONAL
> autoreconf: error: automake failed with exit status: 1
> ```
> 
> Test was to drop these files into a just built directory from current master, then try to reconfigure and rebuild

Sorry but this change doesn't touch `USE_NLS` or `ENABLE_PACKAGEKIT`. Additionally, I can configure normally after rebasing on master?

**Comment by lukefromdc** [comment]
A rebase should fix it

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine, I can compress to a .zst file and then open that. Don't have any test files whose actual mimetype (not just extension-building w libmagic support) is x-zst to try it with though

**Review by vkareh — APPROVED** [review]
LGTM

**Pull request merged**
