### PR TITLE
Fix -Wimplicit-int-conversion warning

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by mbkma — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
@rbuj
Can you please trigger a deployment at travis?

**Comment by rbuj** [comment]
@raveit65 done

**Comment by raveit65** [comment]
Credits are running out again.

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
@rbuj @mbkma 
Do you agree with disabling the annoying `warning: unused parameter` warnings from debian build?
This was more a wish of a former Mate developer which is gone in anger.
Sorry, i don't like to spend my rare spare time any more with scrolling through this tons of warnings in debian CI builds.
If someone like to fix this warnings he can enable the cflag warning parameter in his own local builds.

**Comment by rbuj** [comment]
yes, I agree with this removal

**Comment by mbkma** [comment]
yes, I agree too.

**Comment by raveit65** [comment]
I think we can add this to existing PRs to avoid wasting sponsored build time by travis.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/engrampa/blob/master/.build.yml#L97
We only need to remove the `-Wunused-parameter` compiler flag here.
Maybe we should also remove -Wunused-macros?
No sure about, and i don't think that this flag spams the build logs heavily.

**Comment by rbuj** [comment]
In our repositories, we currently have the warnings listed below:
- clang-debug-mate-desktop.sh  gets the build logs
- clang-debug-warnings.sh  gets the report below about the warning stats
```
[robert@fedora ~]$ ./clang-debug-mate-desktop.sh 
(cut)
[robert@fedora ~]$ ./clang-debug-warnings.sh 
** WARNINGS **

clang version 12.0.1 (Fedora 12.0.1-1.fc34)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

-Wbad-function-cast 48
-Wcast-align 152
-Wcast-function-type 18
-Wconstant-conversion 1
-Wdeprecated-declarations 1636
-Wenum-conversion 24
-Wenum-float-conversion 1
-Wfloat-conversion 944
-Wformat-invalid-specifier 1
-Wformat-nonliteral 94
-Wimplicit-const-int-float-conversion 4
-Wimplicit-float-conversion 117
-Wimplicit-function-declaration 1
-Wimplicit-int-conversion 288
-Wimplicit-int-float-conversion 218
-Wincompatible-function-pointer-types 1
-Wincompatible-pointer-types 2
-Wincompatible-pointer-types-discards-qualifiers 34
-Wint-in-bool-context 2
-Wliteral-conversion 3
-Wlogical-not-parentheses 2
-Wmissing-field-initializers 225
-Wmissing-prototypes 44
-Wpointer-arith 14
-Wpointer-sign 29
-W#pragma-messages 18
-Wself-assign 2
-Wshadow 67
-Wshorten-64-to-32 1019
-Wsign-compare 285
-Wsign-conversion 3811
-Wsometimes-uninitialized 8
-Wstrict-prototypes 31
-Wstring-conversion 39
-Wtautological-overlap-compare 1
-Wuninitialized 2
-Wunused-function 5
-Wunused-macros 626
-Wunused-parameter 7226

Total: 17043/39 (num/types)
```
NOTE: some of the warnings come from other packages which don't belong to the MATE project
NOTE:  most -Wunused-macros come from obsolete marshallers
### clang-debug-mate-desktop.sh
```
#!/bin/bash
BASERAMDIR=$HOME/builddir
BUILDRAMDIR=$BASERAMDIR/test-mate-desktop

export LANG=en_US.UTF-8

sudo dnf upgrade -y --refresh
mkdir -p $BASERAMDIR
NPROC=`nproc`

while read i
do
  echo $i
  BUILDRAMDIR=$BASERAMDIR/$i
  if [[ -d "$BUILDRAMDIR" ]]; then
     cd $BUILDRAMDIR
     echo -ne ' + Pull: '; git pull &> /dev/null && echo OK || echo Failed
  else
     echo -ne ' + Clone: '; git clone --quiet "https://github.com/mate-desktop/"$i".git" $BUILDRAMDIR &> /dev/null && echo OK || echo Failed
     cd $BUILDRAMDIR
     git submodule init
  fi
  git submodule update --recursive --remote
  grep -rl G_GNUC_UNUSED . | xargs sed -i 's/G_GNUC_UNUSED//g'
#  echo -ne ' + tx pull -l ca: '; tx pull -l ca -f &> /dev/null && echo OK || echo Failed
  echo -ne ' + Install build deps: '; sudo dnf builddep -y --quiet $i &> /dev/null && echo OK || echo Failed

  CC="clang"
  CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter"
  CONF="--prefix=/usr"
  case "$i" in
    caja|caja-actions|caja-extensions|caja-dropbox|libmatekbd|libmateweather|mate-indicator-applet|mate-media|mate-netbook|mate-notification-daemon|mate-sensors-applet|mate-settings-daemon|mate-user-share|pluma|python-caja) # missing MATE_DEBUG_CHECK
      CONF+=" --enable-compile-warnings=maximum"
      ;;
    mate-applets)
      CONF+=" --libexecdir=/usr/libexec/mate-applets --enable-compile-warnings=maximum"
      ;;
    engrampa|marco|mate-control-center|mate-desktop|mate-panel|mate-power-manager|mate-polkit|mate-session-manager|mate-screensaver|mate-system-monitor|mate-utils) # MATE_DEBUG_CHECK + MATE_COMPILER_WARNINGS
      CONF+=" --enable-debug --enable-compile-warnings=maximum"
      ;;
    mate-menus)
      CONF+=" --enable-debug --enable-compile-warnings=maximum --disable-collection"
      ;;
    mate-terminal) # MATE_DEBUG_CHECK + MATE_COMPILER_WARNINGS
      CONF+=" --enable-debug --enable-compile-warnings=maximum --disable-smclient"
      ;;
    eom) # enable eom-thumbnailer + MATE_DEBUG_CHECK + MATE_COMPILER_WARNINGS
      CONF+=" --enable-debug --enable-compile-warnings=maximum --enable-thumbnailer --without-gdk-pixbuf-thumbnailer"
      ;;
    atril) # missing MATE_DEBUG_CHECK
      CONF+=" --enable-debug --enable-compile-warnings=maximum  --enable-cxx-warnings=maximum --disable-synctex"
      ;;
    mate-system-monitor) # MATE_DEBUG_CHECK + MATE_COMPILER_WARNINGS + MATE_CXX_WARNINGS
      CONF+=" --enable-debug --enable-compile-warnings=maximum  --enable-cxx-warnings=maximum"
      ;;
    mozo) # missing MATE_DEBUG_CHECK, MATE_COMPILER_WARNINGS
      ;;
  esac
  echo -ne ' + Configure, Make, Install: '; CC=${CC} CFLAGS="${CFLAGS}" ./autogen.sh ${CONF} &> $BASERAMDIR/$i.conf.log && make -j${NPROC} V=1 &> $BASERAMDIR/${i}.make.log && sudo make install &> $BASERAMDIR/${i}.install.log
  if [ $? -eq 0 ]; then
    echo OK
  else
    echo Failed
  fi
done <<< "mate-common
mate-desktop
mate-settings-daemon
mate-notification-daemon
mate-session-manager
atril
caja
caja-actions
caja-extensions
caja-dropbox
engrampa
eom
libmatekbd
libmatemixer
libmateweather
marco
mate-backgrounds
mate-applets
mate-calc
mate-control-center
mate-icon-theme
mate-indicator-applet
mate-media
mate-menus
mate-netbook
mate-panel
mate-polkit
mate-power-manager
mate-screensaver
mate-sensors-applet
mate-system-monitor
mate-terminal
mate-themes
mate-user-guide
mate-utils
mozo
pluma
pluma-plugins
python-caja"
```
### clang-debug-warnings.sh
```
REPORTDIR=$HOME/builddir

echo -ne '** WARNINGS **\n\n'
clang --version
echo ""

total=0
types=0
for warning in $(grep warning ${REPORTDIR}/*.make.log | grep -Po '\[\-W.*\]' | sed 's/[][]//g' | sort -u)
do
 type=${warning#"-W"}
 num=$(echo "grep -F \"[$warning]\" ${REPORTDIR}/*.make.log | sort -u | wc -l" | sh)
 echo "$warning $num"
 total=$(($total + $num))
 types=$(($types + 1))
done
echo "
Total: $total/$types (num/types)
"
```

**Comment by rbuj** [comment]
engrampa warning stats:
```
[robert@fedora ~]$ ~/warnings-file.sh builddir/engrampa.make.log 
-Wcast-align 2
-Wdeprecated-declarations 41
-Wfloat-conversion 28
-Wformat-nonliteral 2
-Wimplicit-function-declaration 1
-Wimplicit-int-conversion 1
-Wimplicit-int-float-conversion 5
-Wincompatible-pointer-types-discards-qualifiers 1
-Wmissing-field-initializers 4
-W#pragma-messages 1
-Wshorten-64-to-32 59
-Wsign-conversion 118
-Wunused-function 3
-Wunused-macros 20
-Wunused-parameter 508
```
### ~/warnings-file.sh
```
FILE=$1
for warning in $(grep warning $FILE | grep -Po '\[\-W.*\]' | sed 's/[][]//g' | sort -u)
do
 type=${warning#"-W"}
 cmd="grep -F \"[$warning]\" $FILE | wc -l"
 num=$(echo $cmd | sh)
 echo "$warning $num"
```

**Comment by raveit65** [comment]
Ok, i think only removing `-Wunused-parameter` from https://github.com/mate-desktop/engrampa/blob/master/.build.yml#L97
should be sufficient.
Can you please add this to existing PRs when you plan do a push already.

**Comment by raveit65** [comment]
Done for this repo.
https://github.com/mate-desktop/engrampa/commit/4a860aca880cda22c6e1d97aa0d6471904943ceb
Build log is readable now.
https://app.travis-ci.com/github/mate-desktop/engrampa/jobs/557585364

**Pull request merged**
