### PR TITLE
Accessibility improvements (labels, screen reading & keyboard navigation)

### PR DESCRIPTION
**Pull request by vvillenave**

### CODE REVIEW

**Comment by raveit65** [comment]
```
[rave@mother engrampa]$ git branch 
  1.18
  1.20
  1.22
  1.24
  1.26
  master
* vvillenave-vv/a11y
[rave@mother engrampa]$ git pull https://github.com/vvillenave/engrampa.git vv/a11y
From https://github.com/vvillenave/engrampa
 * branch            vv/a11y    -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
```
Can you please rebase with master. I can't test it locally.

**Comment by vvillenave** [comment]
> Can you please rebase with master. I can't test it locally.

This should do the trick.

**Comment by raveit65** [comment]
Thanks, just testing.

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
@mate-desktop/core-team 
Anyone else like to review the PR or should i merge it?

**Pull request merged**
