### PR TITLE
Gettext

### PR DESCRIPTION
**Pull request by yetist**
ru.po, sr.po and uk.po has errors.

### CODE REVIEW

**Comment by sc0w** [comment]
The languages are fixed in master with https://github.com/mate-desktop/engrampa/commit/b32d619b93fcaca76db77a6bb9ff419a54e0877c

@yetist you can remove the  commit https://github.com/mate-desktop/engrampa/pull/341/commits/402a8e3357068fe5b0662323c7e64cc5cf07873b and rebase this PR

**Comment by yetist** [comment]
> @yetist you can remove the commit [402a8e3](https://github.com/mate-desktop/engrampa/commit/402a8e3357068fe5b0662323c7e64cc5cf07873b) and rebase this PR

Thank you, done.

**Comment by sc0w** [comment]
@yetist I see in the logs:

`/usr/bin/xgettext: warning: file 'src/ui/menus-toolbars.ui' extension 'ui' is unknown; will try C`

**Comment by raveit65** [comment]
> I see in the logs:

`/usr/bin/xgettext: warning: file 'src/ui/menus-toolbars.ui' extension 'ui' is unknown; will try C`

Report about problems with glade and ui files.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809846

**Pull request merged**
