### PR TITLE
LHA: Fix internet media type

### PR DESCRIPTION
**Pull request by rbuj**
LHA media type is application/x-lzh-compressed
```shell
$ file --mime-type ~/test.lzh
/home/robert/test.lzh: application/x-lzh-compressed
```
test
```shell
$ CFLAGS="-g -O0" ./autogen.sh --enable-magic --enable-packagekit --prefix=/usr && make && sudo make install
$ sudo update-desktop-database /usr/share/applications
$ engrampa ~/test.lzh
```

### CODE REVIEW

**Comment by sc0w** [comment]
Regression detected:

How to reproduce:

- build without `--enable-magic`
- rename file with `.lha` extension to other name, for example `"lhatest"`
- try to open and see:

**Comment by rbuj** [comment]
How do you detect the file type if it doesn't exist yet in the local magic database when libmagic is disabled? Could you do it before?
The entry will be added after merging https://github.com/mate-desktop/engrampa/pull/316

**Comment by rbuj** [comment]
It has been fixed in https://github.com/mate-desktop/engrampa/pull/329

**Comment by sc0w** [comment]
one more regression detected (building without `--enable-magic`):

1. open engrampa
2. drag from caja .lha file and drop to engrampa
3. engrampa can't open the file

@mate-desktop/core-team maybe we must revert https://github.com/mate-desktop/engrampa/commit/09d1ff998680161a3264c06c1ee7f846911cd963 and https://github.com/mate-desktop/engrampa/commit/815e4760c00be51bc41a16ef68ce62298723b59d ?

**Comment by rbuj** [comment]
https://github.com/mate-desktop/engrampa/pull/316 fixes this

**Pull request merged**
