### PR TITLE
Folder /data/ui/ renamed to /src/ui/ in .po files

### PR DESCRIPTION
**Pull request by sc0w**
The folder was changed in https://github.com/mate-desktop/engrampa/commit/0d3a5b087f4bb6c118abe34a14ea27b86583f812

### CODE REVIEW

**Comment by raveit65** [comment]
Does creating engrampa.pot and updating the source at transiflex not not the same job?
@monsta ???

**Comment by sc0w** [comment]
I did it with:

`sed -i "s/data\/ui/src\/ui/g" *`

**Comment by raveit65** [comment]
In a copied repo folder do
'./autogen.sh && make && cd po && make engrampa.pot'
Does the created engrampa.pot contain the right paths?
Such a file we submit to transiflex if strings are changed in code.

**Comment by raveit65** [comment]
Problem is that if we change something in po files it will override by next transiflex update.

**Comment by sc0w** [comment]
aha, `engrampa.pot` seems to be fine

I understand :)

**Comment by raveit65** [comment]
Ok, i will upload the new pot file.

**Pull request closed without merging**
