### PR TITLE
LHA: add test for checking compressed file integrity

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
We have a conflict with master.

**Comment by lukefromdc** [comment]
How do I test this? When I use emgrampa to compress a file, I don't see lha as an option for compressing the file or files. Maybe I'm missing an underlying support library? Is there a test file available?

**Comment by rbuj** [comment]
@lukefromdc Yes, the lha command should be available on your system in order to test this pull request.
```
[robert@localhost ~]$ sudo dnf install -y lha lorem-ipsum-generator
[robert@localhost ~]$ lorem-ipsum-generator -p 20 > 1/a.txt
[robert@localhost ~]$ lorem-ipsum-generator -p 200 > 1/b.txt
[robert@localhost ~]$ lorem-ipsum-generator -p 2000 > 1/c.txt
[robert@localhost ~]$ engrampa -a test.lzh 1
[robert@localhost ~]$ file test.lzh
test.lzh:   LHa 2.x? archive data  [lhd], 'U' OS
```
Open test.lzh file with engrampa, and select Archive -> Test Integrity from application menu.

**Comment by lukefromdc** [comment]
Oh yeah, I found I did not have that installed

**Comment by lukefromdc** [comment]
Even after installing lhasa, liblhasa, and liblhasa-dev on Debian I was unable to compres to nn lzh/lha file, it appeared as .lzh in the list of options but trying to invoke it brought up the "command not found" dialog. Probably I won't be able to test this, out of time for tonight

**Comment by rbuj** [comment]
I added jlha (java lha) command for Ubuntu/Debian https://github.com/mate-desktop/engrampa/pull/328.

- LHA java frontend: https://packages.ubuntu.com/bionic/jlha-utils (provides jlha (jlhafrontend.jar) and requires jlha.jar)
- LHA java lib: https://packages.ubuntu.com/bionic/libjlha-java (provides jlha.jar)

jlha: `java -jar /usr/share/java/jlhafrontend.jar "$@"`

**Comment by sc0w** [comment]
github says: `This branch has conflicts that must be resolved`

**Comment by rbuj** [comment]
The merge conflicts have been resolved.

**Comment by sc0w** [comment]
what means the argument `-q1` ?

**Comment by rbuj** [comment]
```shell
$ la -h
<curt>
commands:                           options:
 a   Add(or replace) to archive      q{num} quiet (num:quiet mode)
<cut>
$ lha t -q1 ~/test.lzh 
1/a.txt - Tested  
1/b.txt - Tested  
1/c.txt - Tested  
$ lha t ~/test.lzh 
1/a.txt	- Tested   :  oo
1/b.txt	- Tested   :  oooooooooooooooo
1/c.txt	- Tested   :  oooooooooooooooooooooooooooooooooooooooo
```

**Comment by sc0w** [comment]
`$ lha --version`
LHa: Error: --version No such file or directory

`$ lha --help`
LHa: Error: --help No such file or directory

`$ lha t test.lha` <- It works

`$ lha t -q1 test.lha `
LHa: Error: -q1 No such file or directory

**Comment by rbuj** [comment]
Are you using jlha?
```
~$ lha
jLHA                       Copyright(C) 2002  Michel Ishizuka
jlhafrontend               Copyright(C) 2006  Ying-Chun Liu
usage: JLHAFrontEnd [-]{axelvudmcpt[q[num]][vnfodizg012]}[w=<dir>] archive_file [file...]
commands:                               options:
 a   Add to archive                      q{num} quiet mode
 x,e Extract from archive                v  verbose
 l,v List / Verbose list                 n  not execute
 u   Update newer files to archive       f  force
 d   Delete from archive                 t  FILES are TEXT files
 m   Move to archive                     o[567] compression method (a/u)
 c   Create new archive                  w=<dir> specify working directory
 p   Print to STDOUT from archive        d  delete files after (a/u/c)
 t   Test archive                        i  ignore directory path (x/e)
                                         z  files not compress (a/u)
                                         0/1/2  header level (a/u)
                                         e  TEXT code convert from/to EUC-JP
                                         y  filename multibyte convert
```

**Comment by sc0w** [comment]
```
$ lha
Lhasa v0.3.1 command line LHA tool  - Copyright (C) 2011,2012 Simon Howard
usage: lha [-]{lvtxe[q{num}][finv]}[w=<dir>] archive_file [file...]
commands:                          options:
 l,v List / Verbose List            f  Force overwrite (no prompt)
 t   Test file CRC in archive       i  Ignore directory path
 x,e Extract from archive           n  Perform dry run
 p   Print to stdout from archive   q{num}  Quiet mode
                                    v  Verbose
                                    w=<dir> Specify extract directory
```

**Comment by sc0w** [comment]
`$ lha tq1 test.lha` <- It works here!

**Comment by sc0w** [comment]
I think we have two options to solve this PR:

- check if `lhasa` or `jlha` is installed

- remove the `q1` argument (the easy way), I have tested and it works here

**Comment by rbuj** [comment]
It removes `-q1` option from command line.

**Pull request merged**
