### PR TITLE
Set the current folder of the file chooser dialog using a local file name

### LINKED ISSUE #134: The folder contents could not be displayed - engrampa with --default-dir and --extract
in a terminal:

`engrampa --default-dir=./anyfolder/ --extract filecompressed
`

bugfolderengrampa

### PR DESCRIPTION
**Pull request by zhuyaliang**
Fix #134

### CODE REVIEW

**Comment by lukefromdc** [comment]
This has literally never been part of my workflow so I can't really wrap my head around the test

**Review by lukefromdc — COMMENTED** [review]
Could not wrap my head around the test as I do not use engrampa from the command line in this way, but I can confirm this builds and didn't break extracting files from an archive from the UI. That however is all I can confirm so this is a comment

**Comment by zhuyaliang** [comment]
@raveit65 ```Filecompressed``` should be a real compressed file
2023-05-15 10-15-53屏幕截图

**Review by raveit65 — COMMENTED** [review]
LGTM,
extracting a compressed file into an existing directory works fine.

**Review by raveit65 — APPROVED** [review]

**Pull request merged**
