### PR TITLE
Zstandard: review/update single file compression

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
We have a conflict with master.

**Comment by lukefromdc** [comment]
How do I test this?

**Comment by rbuj** [comment]
@lukefromdc take a look at the commit bodies.

**Comment by sc0w** [comment]
@rbuj  can you attach `.tar.zst` sample file please?

**Comment by rbuj** [comment]
-a, --auto-compress: use archive suffix to determine the compression program
```
$ tar cavf menta.tar.zst /usr/share/themes/Menta
$ xdg-mime query filetype menta.tar.zst
application/x-zstd
```

**Comment by rbuj** [comment]
The merge conflict has been resolved.

**Comment by stokito** [comment]
@ rbuj and @lukefromdc 
Please revert the commit 920724617e66bcab302c84f2d460cdcd965c14c8
The correct mime type for ZStandard is `application/zstd` and NOT `application/x-zstd`.
The libmagic recently had a bag when it returned the incorrect  `application/x-zstd` but it was recently fixed.

**Comment by stokito** [comment]
It also may be useful to check the similar PR in file-roller https://gitlab.gnome.org/GNOME/file-roller/merge_requests/9

**Comment by rbuj** [comment]
application/x-zstd -> application/zstd, based on [IANA db](https://www.iana.org/assignments/media-types/application/zstd)
- application/x-zstd: from file v5.29 (https://github.com/file/file/commit/5b8826616cb699b69f7a1cc7b5c0cbac4b5bed9b September 16, 2016) up to file v5.37 (https://github.com/file/file/commit/dbca4be3db6a70d8a266accaa9431eabf24f01a6 September 11, 2019)

**Comment by stokito** [comment]
Yep, so will you rollback the change? It would be good to put some comment that it's ok that the mime is `application/zstd` according to IANA

**Comment by monsta** [comment]
@rbuj: file 5.38 has been released (https://github.com/file/file/commit/ec41083645689a787cdd00cb3b5bf578aa79e46c)...

**Comment by rbuj** [comment]
@monsta PR https://github.com/mate-desktop/engrampa/pull/353
on F30:
```shell
$ rpm -qi file-devel | grep Version
Version     : 5.36
$ ./autogen.sh --prefix=/usr --enable-magic
$ cat config.h | tail -2
/* define zstd mime type */
#define ZSTD_MIME_TYPE "application/x-zstd"
$ ./autogen.sh --prefix=/usr --disable-magic
$ cat config.h | tail -2
/* define zstd mime type */
#define ZSTD_MIME_TYPE "application/zstd"
```
on Fedora Rawhide:
```shell
$ rpm -qi file-devel | grep Version
Version     : 5.38
$ ./autogen.sh --prefix=/usr --enable-magic
$ cat config.h | tail -2
/* define zstd mime type */
#define ZSTD_MIME_TYPE "application/zstd"
$ ./autogen.sh --prefix=/usr --disable-magic
$ cat config.h | tail -2
/* define zstd mime type */
#define ZSTD_MIME_TYPE "application/zstd"
```

**Pull request merged**
