### PR TITLE
UI: Remove useless code and file

### PR DESCRIPTION
**Pull request by zhuyaliang**
Remove useless code and files from the UI
```
[test@localhost engrampa]$ git branch 
* master
  remove-useless-code
[test@localhost engrampa]$ grep -rin "AddMenu"
src/ui/menus-toolbars.ui:91:  <popup name="AddMenu">
[test@localhost engrampa]$
```
Next, I will replace ```gtk_action``` with ```g_action``` to fix compilation warnings

### CODE REVIEW

**Comment by raveit65** [comment]
Not tested, but maybe it is this part of the menu.
egrampa

**Comment by zhuyaliang** [comment]
@raveit65 MenuBar uses this：
```
    <menu action="EditMenu">
      <menuitem action="Cut"/>
      <menuitem action="Copy"/>
      <menuitem action="Paste"/>
      <menuitem action="Rename"/>
      <menuitem action="Delete"/>
      <separator/>
      <menuitem action="SelectAll"/>
      <menuitem action="DeselectAll"/>
      <separator/>
      <menuitem action="Find"/>
      <separator/>
      <menuitem action="AddFiles"/>
      <menuitem action="AddFolder"/>
      <separator/>
      <menuitem action="Password"/>
    </menu>
```

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by lukefromdc** [comment]
Be sure when replacing` gtk_action` with `g_action` in a later PR not to lose any menu icons. Note that we now have the new mate image menu item  api's available in mate-desktop 1.27.1

**Review by lukefromdc — APPROVED** [review]
This builds and runs fine. Behavior seems same as master, tested the help/about menu items, adding files from the edit->add file menuitem, compressing and decompressing archives, and made sure a new archive opened correctly. No observable runtime changes so this looks good to go

**Pull request merged**
