### PR TITLE
glib-utils: Remove unused function - g_ptr_array_copy

### PR DESCRIPTION
**Pull request by rbuj**
closes https://github.com/mate-desktop/engrampa/issues/283

### CODE REVIEW

**Comment by raveit65** [comment]
Looks like this is needed to fix ubuntu 19.10 travis CI builds here https://github.com/mate-desktop/engrampa/pull/288

**Comment by monsta** [comment]
> Out of scope, but every function using the g_ namespace is likely to result in a clash like this one, it's not a good idea to have those; they should use a separate prefix.

That's true... we already had similar one at https://github.com/mate-desktop/libmatekbd/pull/49

**Comment by lukefromdc** [comment]
Works here too, I was out of town for a few days and thus backed up

**Comment by raveit65** [comment]
Ok, i will make new release (1.23/1.22).
Building engrampa fails for fedora 31 and rawhide.
https://copr-be.cloud.fedoraproject.org/results/raveit65/MATE-1.23.x/fedora-31-x86_64/01027088-engrampa/build.log.gz

**Pull request merged**
